/**
 * Archetype Definitions
 *
 * 22 Seelen-Archetypen mapped to the Major Arcana.
 * Each archetype includes planet/chakra associations and deep content sections.
 *
 * NOTE: Content fields (wesen, staerken, etc.) contain SHORT PLACEHOLDERS.
 * Full AI-generated content will be added in Task 5.
 */

export interface Archetyp {
  /** Major Arcana number 0-21 */
  id: number;
  /** Matches TarotCard.id from tarot-karten.ts */
  karteId: string;
  /** Unique archetype name e.g. "Die Freie Seele" */
  name: string;
  /** Traditional tarot card name e.g. "Der Narr" */
  karteName: string;
  /** Path to card image */
  image: string;
  /** Planet key matching planeten.ts */
  planet: string;
  /** Chakra key matching chakras.ts */
  chakra: string;
  /** One-sentence identity claim */
  claim: string;
  /** ~200 words about essence (placeholder for now) */
  wesen: string;
  /** ~150 words about strengths (placeholder for now) */
  staerken: string;
  /** ~150 words about shadow side (placeholder for now) */
  schattenSeite: string;
  /** ~150 words about relationships (placeholder for now) */
  inBeziehungen: string;
  /** ~150 words about career (placeholder for now) */
  imBeruf: string;
  /** ~100 words personal message from Elfi (placeholder for now) */
  elfiBotschaft: string;
  /** One power sentence */
  affirmation: string;
}

export const archetypen: Archetyp[] = [
  {
    id: 0,
    karteId: 'narr',
    name: 'Die Freie Seele',
    karteName: 'Der Narr',
    image: '/cards/tarot/major-00-narr.webp',
    planet: 'uranus',
    chakra: 'krone',
    claim: 'Du bist die grenzenlose Freiheit, die mutig ins Unbekannte springt.',
    wesen: 'Die Freie Seele verkörpert den Urgeist der Unschuld und des Neubeginns. Du trägst eine kindliche Neugier in dir, die dich immer wieder aufbrechen lässt. Deine Stärke liegt im Vertrauen auf den Moment.',
    staerken: 'Deine größte Gabe ist dein unerschütterlicher Optimismus und deine Fähigkeit, ohne Angst Neues zu wagen. Du inspirierst andere durch deinen Mut.',
    schattenSeite: 'Manchmal kann deine Unbekümmertheit dazu führen, dass du Verantwortung meidest oder die Konsequenzen deines Handelns nicht bedenkst. Lerne, Freiheit mit Bewusstsein zu verbinden.',
    inBeziehungen: 'In Beziehungen brauchst du Raum und Freiheit. Du liebst spielerisch und unbeschwert, musst aber lernen, dich auch auf Tiefe und Verbindlichkeit einzulassen.',
    imBeruf: 'Du blühst in kreativen und unkonventionellen Berufen auf. Starre Strukturen engen dich ein. Dein Platz ist dort, wo Innovation und Freigeist gefragt sind.',
    elfiBotschaft: 'Liebe Freie Seele, dein Vertrauen ins Leben ist dein größtes Geschenk. Bewahre dir diese Leichtigkeit, aber vergiss nicht, auch Wurzeln zu schlagen.',
    affirmation: 'Ich vertraue dem Fluss des Lebens und springe mutig in mein nächstes Abenteuer.',
  },
  {
    id: 1,
    karteId: 'magier',
    name: 'Der Schöpfer',
    karteName: 'Der Magier',
    image: '/cards/tarot/major-01-magier.webp',
    planet: 'merkur',
    chakra: 'hals',
    claim: 'Du bist die schöpferische Kraft, die Visionen in Realität verwandelt.',
    wesen: 'Der Schöpfer verbindet Himmel und Erde durch seine Willenskraft. Du hast die Gabe, aus dem Nichts etwas Wunderbares zu erschaffen. Alle Elemente stehen dir zur Verfügung.',
    staerken: 'Deine Stärke liegt in deiner Manifestationskraft und deinem scharfen Verstand. Du kannst komplexe Ideen in greifbare Ergebnisse verwandeln.',
    schattenSeite: 'Die Gefahr liegt in Manipulation oder der Illusion, alles kontrollieren zu können. Achte darauf, deine Kraft ethisch und im Dienst des Guten einzusetzen.',
    inBeziehungen: 'Du bist ein faszinierender Partner, der andere mit seinem Charisma begeistert. Lerne, auch Verletzlichkeit zuzulassen und nicht alles steuern zu wollen.',
    imBeruf: 'Du bist für Führungspositionen und kreative Unternehmungen geboren. Dort, wo Kommunikation und Innovation gefragt sind, bist du in deinem Element.',
    elfiBotschaft: 'Lieber Schöpfer, du trägst alle Werkzeuge bereits in dir. Nutze sie weise und erschaffe die Welt, die du dir wünschst.',
    affirmation: 'Ich bin der bewusste Schöpfer meiner Realität und manifestiere meine höchste Vision.',
  },
  {
    id: 2,
    karteId: 'hohepriesterin',
    name: 'Die Seherin',
    karteName: 'Die Hohepriesterin',
    image: '/cards/tarot/major-02-hohepriesterin.webp',
    planet: 'mond',
    chakra: 'stirn',
    claim: 'Du bist die stille Wissende, die zwischen den Welten wandelt.',
    wesen: 'Die Seherin hütet das verborgene Wissen und die Mysterien des Lebens. Deine Intuition ist dein stärkstes Werkzeug. Du spürst Wahrheiten, bevor sie sichtbar werden.',
    staerken: 'Deine tiefe Intuition und dein Zugang zum Unbewussten machen dich zu einer weisen Beraterin. Du erkennst Muster, die anderen verborgen bleiben.',
    schattenSeite: 'Dein Rückzug in innere Welten kann dich von der Realität entfremden. Achte darauf, dein Wissen auch aktiv in die Welt zu tragen.',
    inBeziehungen: 'Du brauchst einen Partner, der deine Tiefe respektiert und dir Raum für Stille gibt. Deine Liebe ist tief, aber du zeigst sie auf leise Weise.',
    imBeruf: 'Berufe in Beratung, Heilung oder Forschung liegen dir. Überall dort, wo Tiefgang und Intuition gefragt sind, findest du deine Berufung.',
    elfiBotschaft: 'Liebe Seherin, dein inneres Wissen ist ein Schatz. Vertraue deiner Stimme und teile deine Einsichten mit der Welt.',
    affirmation: 'Ich vertraue meiner inneren Weisheit und lasse mich von meiner Intuition führen.',
  },
  {
    id: 3,
    karteId: 'herrscherin',
    name: 'Die Nährende',
    karteName: 'Die Herrscherin',
    image: '/cards/tarot/major-03-herrscherin.webp',
    planet: 'venus',
    chakra: 'herz',
    claim: 'Du bist die liebende Fülle, die Leben erblühen lässt.',
    wesen: 'Die Nährende verkörpert die Kraft der Natur und der bedingungslosen Liebe. Du schaffst Räume, in denen andere wachsen können. Deine Präsenz ist heilend und nährend.',
    staerken: 'Deine Fähigkeit, andere zu nähren und Fülle zu erschaffen, ist unvergleichlich. Du verbindest Kreativität mit praktischer Fürsorge.',
    schattenSeite: 'Die Gefahr liegt darin, dich selbst zu vernachlässigen oder andere zu erdrücken. Lerne, auch dir selbst diese Fürsorge zu schenken.',
    inBeziehungen: 'Du liebst tief und hingebungsvoll. Dein Partner fühlt sich bei dir geborgen. Achte darauf, deine eigenen Bedürfnisse nicht zu übergehen.',
    imBeruf: 'Du glänzt in fürsorglichen, kreativen oder naturnahen Berufen. Überall, wo Wachstum gefördert wird, bist du am richtigen Platz.',
    elfiBotschaft: 'Liebe Nährende, dein Herz ist ein Garten der Liebe. Vergiss nicht, auch die eigene Blüte zu pflegen.',
    affirmation: 'Ich bin die Quelle der Fülle und lasse Liebe durch mich fließen.',
  },
  {
    id: 4,
    karteId: 'herrscher',
    name: 'Der Souverän',
    karteName: 'Der Herrscher',
    image: '/cards/tarot/major-04-herrscher.webp',
    planet: 'mars',
    chakra: 'solarplexus',
    claim: 'Du bist die ordnende Kraft, die mit klarer Vision Strukturen erschafft.',
    wesen: 'Der Souverän steht für Stabilität, Führung und die Fähigkeit, Visionen in feste Strukturen zu gießen. Du gibst anderen Halt und Orientierung.',
    staerken: 'Deine natürliche Autorität und dein strategisches Denken machen dich zu einem verlässlichen Anführer. Du schaffst Ordnung aus dem Chaos.',
    schattenSeite: 'Starre Kontrolle und Dominanz können dein Schatten sein. Lerne, Macht mit Mitgefühl zu verbinden und Kontrolle auch loszulassen.',
    inBeziehungen: 'Du bist ein beschützender und verlässlicher Partner. Achte darauf, deinem Gegenüber auch Raum für eigene Entscheidungen zu lassen.',
    imBeruf: 'Führungspositionen sind wie für dich gemacht. Du bringst Struktur, Verantwortung und Vision in jedes Projekt.',
    elfiBotschaft: 'Lieber Souverän, wahre Stärke zeigt sich nicht in Kontrolle, sondern im Mut, auch Verletzlichkeit zuzulassen.',
    affirmation: 'Ich führe mit Weisheit und Stärke und erschaffe sichere Räume für andere.',
  },
  {
    id: 5,
    karteId: 'hierophant',
    name: 'Der Weise',
    karteName: 'Der Hierophant',
    image: '/cards/tarot/major-05-hierophant.webp',
    planet: 'venus',
    chakra: 'hals',
    claim: 'Du bist der Brückenbauer zwischen Tradition und höherer Erkenntnis.',
    wesen: 'Der Weise verbindet irdisches Wissen mit spiritueller Erkenntnis. Du bist ein natürlicher Lehrer und Mentor, der andere auf ihrem Weg begleitet.',
    staerken: 'Deine Gabe liegt im Lehren und Weitergeben von Weisheit. Du kannst komplexe spirituelle Wahrheiten verständlich machen.',
    schattenSeite: 'Dogmatismus und starre Überzeugungen können dein Schatten sein. Bleibe offen für neue Wege und Perspektiven jenseits der Tradition.',
    inBeziehungen: 'Du suchst tiefgründige, sinnvolle Verbindungen. Dein Partner muss dein Bedürfnis nach geistigem Austausch teilen.',
    imBeruf: 'Lehre, Beratung und spirituelle Arbeit sind deine Berufung. Du wirkst überall dort, wo Weisheit gefragt ist.',
    elfiBotschaft: 'Lieber Weiser, dein Wissen ist ein Geschenk. Teile es mit offenem Herzen, aber bleibe selbst immer auch Schüler.',
    affirmation: 'Ich verbinde alte Weisheit mit neuer Erkenntnis und teile mein Wissen mit Demut.',
  },
  {
    id: 6,
    karteId: 'liebenden',
    name: 'Die Verbundene',
    karteName: 'Die Liebenden',
    image: '/cards/tarot/major-06-liebenden.webp',
    planet: 'merkur',
    chakra: 'herz',
    claim: 'Du bist die Kraft der Verbindung, die durch Liebe Einheit schafft.',
    wesen: 'Die Verbundene lebt für authentische Verbindung und die Vereinigung von Gegensätzen. Dein Herz strebt nach Harmonie und tiefer, wahrer Liebe.',
    staerken: 'Deine Fähigkeit, Brücken zwischen Menschen zu bauen und Harmonie zu schaffen, ist außergewöhnlich. Du spürst, was andere brauchen.',
    schattenSeite: 'Entscheidungsangst und die Tendenz, dich über andere zu definieren, können dein Schatten sein. Lerne, auch allein vollständig zu sein.',
    inBeziehungen: 'Beziehungen sind dein Lebensthema. Du liebst leidenschaftlich und suchst die Seelenverwandtschaft. Achte auf deine eigene Identität.',
    imBeruf: 'Du blühst in Teamarbeit und vermittelnden Rollen auf. Berufe, die mit Beziehungen und Harmonie zu tun haben, liegen dir.',
    elfiBotschaft: 'Liebe Verbundene, die wichtigste Beziehung ist die zu dir selbst. Aus dieser Liebe heraus fließt alles andere.',
    affirmation: 'Ich wähle bewusst die Liebe und verbinde mich authentisch mit dem Leben.',
  },
  {
    id: 7,
    karteId: 'wagen',
    name: 'Die Siegerin',
    karteName: 'Der Wagen',
    image: '/cards/tarot/major-07-wagen.webp',
    planet: 'mond',
    chakra: 'solarplexus',
    claim: 'Du bist die triumphierende Kraft, die jedes Hindernis überwindet.',
    wesen: 'Die Siegerin vereint Willenskraft mit emotionaler Tiefe. Du fährst deinen Wagen mit Entschlossenheit durch alle Herausforderungen und erreichst deine Ziele.',
    staerken: 'Deine unerschütterliche Willenskraft und dein Fokus tragen dich durch jede Krise. Du verwandelst Widerstand in Antrieb.',
    schattenSeite: 'Überambition und die Unfähigkeit innezuhalten können dein Schatten sein. Lerne, dass Stillstand kein Versagen ist.',
    inBeziehungen: 'Du bist ein leidenschaftlicher Partner mit großem Beschützerinstinkt. Achte darauf, die Beziehung nicht wie ein Projekt zu führen.',
    imBeruf: 'Du bist für herausfordernde Karrieren gemacht. Überall, wo Durchsetzungskraft und Zielstrebigkeit gefragt sind, glänzt du.',
    elfiBotschaft: 'Liebe Siegerin, dein Wille ist deine Superkraft. Aber wahre Siege kommen nicht nur aus dem Kopf, sondern auch aus dem Herzen.',
    affirmation: 'Ich lenke mein Leben mit klarer Absicht und fahre siegreich meinen Weg.',
  },
  {
    id: 8,
    karteId: 'kraft',
    name: 'Die Unbezwingbare',
    karteName: 'Die Kraft',
    image: '/cards/tarot/major-08-kraft.webp',
    planet: 'sonne',
    chakra: 'solarplexus',
    claim: 'Du bist die sanfte Macht, die mit Liebe selbst den Löwen zähmt.',
    wesen: 'Die Unbezwingbare vereint innere Stärke mit Sanftmut. Deine wahre Kraft liegt nicht in Dominanz, sondern in der liebevollen Meisterung deiner inneren Natur.',
    staerken: 'Dein Mut und deine Ausdauer sind bemerkenswert. Du gehst mit Anmut durch schwierige Situationen und inspirierst durch deine Gelassenheit.',
    schattenSeite: 'Unterdrückte Emotionen und die Weigerung, Schwäche zu zeigen, können dein Schatten sein. Wahre Stärke schließt Verletzlichkeit ein.',
    inBeziehungen: 'Du bist eine warmherzige und loyale Partnerin. Deine Geduld und innere Ruhe schaffen einen sicheren Hafen für andere.',
    imBeruf: 'Du meisterst anspruchsvolle Berufe mit Anmut. Positionen, die Ausdauer und emotionale Intelligenz erfordern, sind deine Stärke.',
    elfiBotschaft: 'Liebe Unbezwingbare, deine Kraft liegt in deinem offenen Herzen. Erlaube dir auch, Schwäche zu zeigen.',
    affirmation: 'Meine wahre Kraft liegt in meinem Herzen, und mit Liebe bin ich unbesiegbar.',
  },
  {
    id: 9,
    karteId: 'eremit',
    name: 'Die Suchende',
    karteName: 'Der Eremit',
    image: '/cards/tarot/major-09-eremit.webp',
    planet: 'merkur',
    chakra: 'stirn',
    claim: 'Du bist das innere Licht, das in der Stille die tiefsten Wahrheiten findet.',
    wesen: 'Die Suchende wandelt auf dem Pfad der inneren Erkenntnis. Du trägst die Laterne der Weisheit und findest Antworten dort, wo andere nur Dunkelheit sehen.',
    staerken: 'Deine Fähigkeit zur Selbstreflexion und dein analytischer Geist machen dich zur Finderin verborgener Wahrheiten. Du denkst tiefer als andere.',
    schattenSeite: 'Isolation und übermäßiger Rückzug können dein Schatten sein. Achte darauf, dein Licht auch nach außen zu tragen.',
    inBeziehungen: 'Du brauchst einen Partner, der dein Bedürfnis nach Alleinsein respektiert. Deine Liebe ist tief, aber du brauchst Zeit für dich.',
    imBeruf: 'Forschung, Analyse und Beratung liegen dir. Du arbeitest am besten in Ruhe und mit Autonomie.',
    elfiBotschaft: 'Liebe Suchende, die Antworten liegen in dir. Aber vergiss nicht, dein Licht auch mit anderen zu teilen.',
    affirmation: 'In der Stille finde ich meine tiefste Wahrheit und trage mein Licht in die Welt.',
  },
  {
    id: 10,
    karteId: 'schicksal',
    name: 'Die Schicksalsweberin',
    karteName: 'Rad des Schicksals',
    image: '/cards/tarot/major-10-schicksal.webp',
    planet: 'jupiter',
    chakra: 'solarplexus',
    claim: 'Du bist die kosmische Tänzerin, die im Rhythmus des Lebens ihren Faden spinnt.',
    wesen: 'Die Schicksalsweberin versteht die Zyklen des Lebens und tanzt mit dem ewigen Wandel. Du weißt, dass jede Wendung des Rades einen tieferen Sinn hat.',
    staerken: 'Deine Anpassungsfähigkeit und dein Glück im richtigen Moment machen dich besonders. Du erkennst Chancen in Veränderungen.',
    schattenSeite: 'Passivität und blinder Schicksalsglaube können dein Schatten sein. Erkenne, dass du das Rad aktiv mitdrehen kannst.',
    inBeziehungen: 'Du akzeptierst die Höhen und Tiefen der Liebe. Dein Partner erlebt mit dir eine dynamische, niemals langweilige Beziehung.',
    imBeruf: 'Dynamische Berufe mit Abwechslung liegen dir. Du passt dich schnell an und findest in jeder Situation deinen Platz.',
    elfiBotschaft: 'Liebe Schicksalsweberin, das Rad dreht sich immer weiter. Vertraue darauf, dass du genau dort bist, wo du sein sollst.',
    affirmation: 'Ich fließe mit den Zyklen des Lebens und webe mein Schicksal mit goldenen Fäden.',
  },
  {
    id: 11,
    karteId: 'gerechtigkeit',
    name: 'Die Gerechte',
    karteName: 'Gerechtigkeit',
    image: '/cards/tarot/major-11-gerechtigkeit.webp',
    planet: 'venus',
    chakra: 'herz',
    claim: 'Du bist die Stimme der Wahrheit, die mit Klarheit und Mitgefühl urteilt.',
    wesen: 'Die Gerechte strebt nach Ausgleich und Fairness in allen Lebensbereichen. Du trägst eine innere Waage, die Wahrheit von Illusion unterscheidet.',
    staerken: 'Dein ausgeprägter Gerechtigkeitssinn und deine Fähigkeit, ausgewogene Entscheidungen zu treffen, machen dich zur vertrauenswürdigen Richterin.',
    schattenSeite: 'Perfektionismus und unnachgiebige Strenge können dein Schatten sein. Lerne, auch dir selbst und anderen Gnade zu gewähren.',
    inBeziehungen: 'Du suchst faire und ausgewogene Partnerschaften. Gleichberechtigung ist dir wichtiger als alles andere.',
    imBeruf: 'Recht, Mediation und ethische Führung sind deine Domäne. Du bringst Fairness in jede Organisation.',
    elfiBotschaft: 'Liebe Gerechte, Gerechtigkeit beginnt bei dir selbst. Urteile nicht zu streng über dich und die Welt.',
    affirmation: 'Ich bringe Wahrheit und Ausgleich in mein Leben und handle mit Integrität.',
  },
  {
    id: 12,
    karteId: 'gehaengte',
    name: 'Die Wandlerin',
    karteName: 'Der Gehängte',
    image: '/cards/tarot/major-12-gehaengte.webp',
    planet: 'neptun',
    chakra: 'krone',
    claim: 'Du bist die weise Loslassende, die in der Hingabe die höchste Freiheit findet.',
    wesen: 'Die Wandlerin sieht die Welt aus einer völlig neuen Perspektive. Durch das Loslassen alter Sichtweisen gewinnst du tiefe spirituelle Einsichten.',
    staerken: 'Deine Fähigkeit, loszulassen und Dinge aus einer neuen Perspektive zu betrachten, ist deine größte Gabe. Du findest Frieden im Nicht-Tun.',
    schattenSeite: 'Märtyrerverhalten und passive Selbstaufgabe können dein Schatten sein. Unterscheide zwischen bewusstem Loslassen und hilflosem Aufgeben.',
    inBeziehungen: 'Du bist bereit, für die Liebe Opfer zu bringen. Achte darauf, dass es bewusste Hingabe ist und nicht Selbstverleugnung.',
    imBeruf: 'Kreative und spirituelle Berufe liegen dir. Du findest innovative Lösungen, weil du Probleme anders betrachtest als andere.',
    elfiBotschaft: 'Liebe Wandlerin, im Loslassen liegt deine Kraft. Vertraue darauf, dass die neue Perspektive dir den Weg zeigt.',
    affirmation: 'Ich lasse los und empfange. In der Hingabe finde ich meine wahre Freiheit.',
  },
  {
    id: 13,
    karteId: 'tod',
    name: 'Die Transformatorin',
    karteName: 'Der Tod',
    image: '/cards/tarot/major-13-tod.webp',
    planet: 'pluto',
    chakra: 'wurzel',
    claim: 'Du bist die Kraft der Erneuerung, die durch jedes Ende einen strahlenden Neuanfang gebiert.',
    wesen: 'Die Transformatorin versteht, dass wahre Erneuerung nur durch das Loslassen des Alten möglich ist. Du bist die Meisterin der Wandlung und des Neubeginns.',
    staerken: 'Deine Fähigkeit, Altes hinter dir zu lassen und dich völlig neu zu erfinden, ist außergewöhnlich. Du hilfst auch anderen bei ihren Übergängen.',
    schattenSeite: 'Destruktivität oder die Angst vor dem Ende können dein Schatten sein. Lerne, Transformation sanft und bewusst zu gestalten.',
    inBeziehungen: 'Du erlebst Beziehungen intensiv und transformierend. Jede Verbindung verändert dich. Achte auf gesunde Grenzen.',
    imBeruf: 'Krisenmanagement, Transformation und Heilarbeit liegen dir. Du bist dort am stärksten, wo tiefgreifender Wandel gebraucht wird.',
    elfiBotschaft: 'Liebe Transformatorin, jedes Ende ist ein Anfang. Du bist die Phönix-Energie, die aus der Asche aufsteigt.',
    affirmation: 'Ich umarme die Wandlung und erstehe aus jeder Veränderung stärker und strahlender.',
  },
  {
    id: 14,
    karteId: 'maessigung',
    name: 'Die Alchemistin',
    karteName: 'Mäßigung',
    image: '/cards/tarot/major-14-maessigung.webp',
    planet: 'jupiter',
    chakra: 'sakral',
    claim: 'Du bist die harmonische Mitte, die aus Gegensätzen Gold erschafft.',
    wesen: 'Die Alchemistin verbindet Gegensätze zu etwas Neuem und Höherem. Du findest den goldenen Mittelweg und verwandelst Konflikte in Harmonie.',
    staerken: 'Deine Geduld und dein Gespür für Balance machen dich zur Meisterin der Harmonie. Du weißt, wie man verschiedene Energien vereint.',
    schattenSeite: 'Übermäßige Kompromissbereitschaft und die Vermeidung von Konflikten können dein Schatten sein. Manchmal braucht es klare Kanten.',
    inBeziehungen: 'Du schaffst harmonische Partnerschaften durch deine ausgleichende Art. Achte darauf, auch deine eigenen Bedürfnisse klar zu benennen.',
    imBeruf: 'Mediation, Heilkunde und kreative Berufe liegen dir. Überall, wo verschiedene Kräfte in Einklang gebracht werden müssen.',
    elfiBotschaft: 'Liebe Alchemistin, du bist die Meisterin der Balance. Vergiss nicht, dass Harmonie auch mutige Entscheidungen braucht.',
    affirmation: 'Ich bin die Alchemistin meines Lebens und verwandle jede Erfahrung in Gold.',
  },
  {
    id: 15,
    karteId: 'teufel',
    name: 'Die Befreierin',
    karteName: 'Der Teufel',
    image: '/cards/tarot/major-15-teufel.webp',
    planet: 'saturn',
    chakra: 'wurzel',
    claim: 'Du bist die mutige Kraft, die Ketten sprengt und verborgene Wahrheiten ans Licht bringt.',
    wesen: 'Die Befreierin kennt die dunklen Seiten des Lebens und hat keine Angst vor ihnen. Du durchschaust Illusionen und Abhängigkeiten und führst dich und andere in die Freiheit.',
    staerken: 'Dein Mut, dich deinen Schatten zu stellen, macht dich unglaublich stark. Du hilfst anderen, ihre eigenen Fesseln zu erkennen und zu lösen.',
    schattenSeite: 'Selbstzerstörerische Muster und die Sucht nach Extremen können dein Schatten sein. Lerne, Befreiung nicht mit Rebellion zu verwechseln.',
    inBeziehungen: 'Du liebst intensiv und leidenschaftlich. Achte auf gesunde Grenzen und erkenne, wann Leidenschaft in Abhängigkeit kippt.',
    imBeruf: 'Psychologie, Suchtberatung und transformative Arbeit liegen dir. Du bist dort am stärksten, wo echte Befreiung gebraucht wird.',
    elfiBotschaft: 'Liebe Befreierin, die größte Befreiung ist die von deinen eigenen Ängsten. Du bist stärker als jede Kette.',
    affirmation: 'Ich befreie mich von allen Fesseln und stehe in meiner vollen, ungezähmten Kraft.',
  },
  {
    id: 16,
    karteId: 'turm',
    name: 'Die Erwachende',
    karteName: 'Der Turm',
    image: '/cards/tarot/major-16-turm.webp',
    planet: 'mars',
    chakra: 'wurzel',
    claim: 'Du bist der Blitz der Erkenntnis, der falsche Strukturen niederreißt und Platz für Neues schafft.',
    wesen: 'Die Erwachende bringt plötzliche Klarheit und die Kraft des Umbruchs. Du zerstörst nur, was nicht mehr dient, um Raum für Authentisches zu schaffen.',
    staerken: 'Deine Fähigkeit, die Wahrheit zu erkennen und danach zu handeln, auch wenn es unbequem ist, macht dich zur Katalysatorin des Wandels.',
    schattenSeite: 'Destruktivität und die Sucht nach Drama können dein Schatten sein. Lerne, Veränderung auch sanft einzuleiten.',
    inBeziehungen: 'Du bringst Ehrlichkeit und Intensität in Beziehungen. Achte darauf, nicht alles niederzureißen, nur weil es imperfekt ist.',
    imBeruf: 'Krisenmanagement, Revolution und Umstrukturierung liegen dir. Du bist der Katalysator, den Organisationen im Umbruch brauchen.',
    elfiBotschaft: 'Liebe Erwachende, der Turm fällt, damit du freier stehen kannst. Vertraue dem Prozess der Erneuerung.',
    affirmation: 'Ich lasse los, was nicht mehr dient, und baue auf den Trümmern mein authentisches Leben.',
  },
  {
    id: 17,
    karteId: 'stern',
    name: 'Die Hoffnungsträgerin',
    karteName: 'Der Stern',
    image: '/cards/tarot/major-17-stern.webp',
    planet: 'uranus',
    chakra: 'krone',
    claim: 'Du bist das kosmische Licht, das in der dunkelsten Nacht den Weg weist.',
    wesen: 'Die Hoffnungsträgerin bringt Licht und Inspiration in die Welt. Nach jedem Sturm bist du der Stern, der am Horizont aufgeht und Heilung bringt.',
    staerken: 'Dein unerschütterlicher Glaube an das Gute und deine heilende Präsenz sind deine größten Gaben. Du inspirierst andere zu hoffen.',
    schattenSeite: 'Naivität und die Flucht in Idealismus können dein Schatten sein. Bleibe geerdet, während du nach den Sternen greifst.',
    inBeziehungen: 'Du bringst Heilung und Inspiration in jede Verbindung. Dein Partner fühlt sich von deinem Licht angezogen und getröstet.',
    imBeruf: 'Heilende, künstlerische und humanitäre Berufe liegen dir. Du wirkst überall dort, wo Hoffnung und Inspiration gebraucht werden.',
    elfiBotschaft: 'Liebe Hoffnungsträgerin, dein Licht scheint auch dann, wenn du es selbst nicht siehst. Du bist der Stern für viele.',
    affirmation: 'Ich bin ein Stern am Himmel des Lebens und bringe Licht und Hoffnung in die Welt.',
  },
  {
    id: 18,
    karteId: 'mond',
    name: 'Die Traumwandlerin',
    karteName: 'Der Mond',
    image: '/cards/tarot/major-18-mond.webp',
    planet: 'neptun',
    chakra: 'stirn',
    claim: 'Du bist die Reisende zwischen den Welten, die im Mondlicht verborgene Pfade findet.',
    wesen: 'Die Traumwandlerin bewegt sich zwischen Traum und Realität. Dein Zugang zum Unbewussten ist tiefer als bei den meisten Menschen. Du spürst die verborgenen Strömungen.',
    staerken: 'Deine tiefe Empathie und dein Zugang zu Träumen und Visionen machen dich zu einer begnadeten Seherin. Du erkennst, was unter der Oberfläche liegt.',
    schattenSeite: 'Ängste, Illusionen und die Flucht in Fantasiewelten können dein Schatten sein. Lerne, zwischen Intuition und Angst zu unterscheiden.',
    inBeziehungen: 'Du liebst tief und empfindsam. Dein Partner muss deine emotionale Tiefe aushalten können. Achte auf klare Kommunikation.',
    imBeruf: 'Kunst, Psychologie und spirituelle Berufe liegen dir. Überall dort, wo das Unbewusste erforscht wird, bist du zuhause.',
    elfiBotschaft: 'Liebe Traumwandlerin, deine Sensibilität ist ein Geschenk. Lerne, zwischen den Stimmen der Angst und der Intuition zu unterscheiden.',
    affirmation: 'Ich wandle sicher durch die Nacht und vertraue meiner inneren Führung.',
  },
  {
    id: 19,
    karteId: 'sonne',
    name: 'Die Strahlende',
    karteName: 'Die Sonne',
    image: '/cards/tarot/major-19-sonne.webp',
    planet: 'sonne',
    chakra: 'solarplexus',
    claim: 'Du bist die strahlende Lebensfreude, die jeden Raum mit Licht und Wärme erfüllt.',
    wesen: 'Die Strahlende verkörpert pure Lebensfreude und Vitalität. Dein Licht wärmt und erhellt das Leben aller, die dir begegnen. Du bist die Sonne selbst.',
    staerken: 'Dein ansteckender Optimismus und deine Lebensfreude sind deine größten Gaben. Du bringst Licht in jede Situation und hebst andere auf.',
    schattenSeite: 'Die Unfähigkeit, Dunkelheit und Schmerz anzuerkennen, kann dein Schatten sein. Wahres Licht entsteht nur, wenn du auch die Nacht akzeptierst.',
    inBeziehungen: 'Du bist eine lebhafte und großzügige Partnerin. Dein Enthusiasmus ist ansteckend. Achte darauf, auch leise Töne zuzulassen.',
    imBeruf: 'Performance, Führung und Motivationsarbeit liegen dir. Du bist das Zentrum, um das sich alles dreht.',
    elfiBotschaft: 'Liebe Strahlende, dein Licht ist wunderschön. Erlaube dir auch, Schatten zu haben, denn sie machen dein Strahlen erst real.',
    affirmation: 'Ich strahle von innen heraus und teile meine Freude und mein Licht mit der Welt.',
  },
  {
    id: 20,
    karteId: 'gericht',
    name: 'Die Berufene',
    karteName: 'Das Gericht',
    image: '/cards/tarot/major-20-gericht.webp',
    planet: 'pluto',
    chakra: 'wurzel',
    claim: 'Du bist der Ruf der Seele, der aus der Tiefe aufsteigt und dein wahres Selbst erweckt.',
    wesen: 'Die Berufene hört den inneren Ruf und folgt ihrer höheren Bestimmung. Du bist hier, um andere zu erwecken und an ihre eigene Berufung zu erinnern.',
    staerken: 'Deine Fähigkeit, andere zu inspirieren und zu erwecken, ist einzigartig. Du erkennst das verborgene Potenzial in jedem Menschen.',
    schattenSeite: 'Selbstgerechtigkeit und das Gefühl, über andere urteilen zu dürfen, können dein Schatten sein. Wahre Berufung kommt aus Demut.',
    inBeziehungen: 'Du suchst Beziehungen, die deine Seele berühren und transformieren. Oberflächlichkeit langweilt dich schnell.',
    imBeruf: 'Coaching, Seelsorge und transformative Führung liegen dir. Du weckst das Beste in anderen auf.',
    elfiBotschaft: 'Liebe Berufene, dein Ruf kommt von ganz tief innen. Folge ihm mit Vertrauen und Demut.',
    affirmation: 'Ich höre den Ruf meiner Seele und folge meiner höchsten Bestimmung mit Vertrauen.',
  },
  {
    id: 21,
    karteId: 'welt',
    name: 'Die Vollendete',
    karteName: 'Die Welt',
    image: '/cards/tarot/major-21-welt.webp',
    planet: 'saturn',
    chakra: 'krone',
    claim: 'Du bist die tanzende Einheit, die alle Erfahrungen zu einem vollkommenen Ganzen vereint.',
    wesen: 'Die Vollendete hat den gesamten Kreislauf durchlaufen und alle Lektionen integriert. Du tanzt im Zentrum des Universums und verkörperst kosmische Ganzheit.',
    staerken: 'Deine Fähigkeit, das große Ganze zu sehen und alle Teile zu integrieren, ist unvergleichlich. Du bringst Vollendung in alles, was du berührst.',
    schattenSeite: 'Die Angst vor dem nächsten Zyklus und das Festhalten an Erreichtem können dein Schatten sein. Vollendung ist kein Endpunkt.',
    inBeziehungen: 'Du suchst eine Partnerschaft, die auf Gleichwertigkeit und gegenseitigem Wachstum basiert. Du brauchst jemanden, der auf Augenhöhe tanzt.',
    imBeruf: 'Du bist für Positionen prädestiniert, die Überblick und Integration erfordern. Du bringst Projekte zum Abschluss wie keine andere.',
    elfiBotschaft: 'Liebe Vollendete, du hast so viel erreicht. Feiere dich und erlaube dir, den nächsten Tanz zu beginnen.',
    affirmation: 'Ich bin ganz und vollständig. Ich tanze im Rhythmus des Universums und feiere mein Sein.',
  },
];

// ---------------------------------------------------------------------------
// Helper
// ---------------------------------------------------------------------------

/**
 * Get an archetype by its Major Arcana ID (0-21).
 * Throws if the ID is not found.
 */
export function getArchetyp(id: number): Archetyp {
  const archetyp = archetypen.find((a) => a.id === id);
  if (!archetyp) {
    throw new Error(`Archetyp with id ${id} not found`);
  }
  return archetyp;
}
