/**
 * Planet Definitions
 *
 * Celestial body associations for the Seelen-Profil system.
 * Each planet carries a specific energy that influences the archetype.
 */

export interface PlanetInfo {
  /** Unique planet key */
  id: string;
  /** Display name */
  name: string;
  /** Astronomical/astrological symbol */
  symbol: string;
  /** Short 1-sentence energy description */
  energie: string;
  /** Rich, evocative description of the planet's meaning (~200+ words) */
  beschreibung: string;
  /** Personal message from the planet to the soul (~100 words) */
  botschaft: string;
  /** Concrete spiritual ritual associated with this planet (~80 words) */
  ritual: string;
}

export const planeten: Record<string, PlanetInfo> = {
  sonne: {
    id: 'sonne',
    name: 'Sonne',
    symbol: '☉',
    energie: 'Vitalität, Lebenskraft und Selbstausdruck',
    beschreibung:
      'Die Sonne ist nicht einfach nur ein Himmelskörper in deinem kosmischen Bauplan -- sie ist das pulsierende Herz deines Wesens, der strahlende Kern, um den sich alles dreht. Wenn du dich jemals gefragt hast, wer du wirklich bist, jenseits aller Rollen, die du spielst, jenseits aller Masken, die du trägst -- dann spürst du die Sehnsucht deiner Sonne, endlich gesehen zu werden.\n\nStell dir vor, tief in deiner Brust brennt ein Feuer, das niemals erlischt. Es ist deine Lebenskraft, dein innerster Antrieb, deine unverwechselbare Essenz. Manche Menschen spüren dieses Feuer als leises, warmes Glühen, andere als lodernde Flamme. Doch gleich, wie es sich in dir zeigt -- es ist immer da. Es hat dich durch jede dunkle Nacht getragen, durch jeden Zweifel, durch jede Krise. Denn die Sonne in dir kennt keine Dunkelheit, die sie nicht durchdringen könnte.\n\nPsychologisch betrachtet verkörpert die Sonne dein Ego im besten Sinne -- nicht das aufgeblähte Ego, das sich über andere erhebt, sondern das gesunde Selbstgefühl, das weiß: Ich bin es wert, zu leuchten. Ich darf Raum einnehmen. Mein Licht nimmt niemandem etwas weg, sondern entzündet das Licht in anderen. Viele von uns haben gelernt, ihr Strahlen zu dimmen, um anderen nicht zu viel zu werden. Die Sonne aber flüstert dir zu: Dein volles Licht ist genau das, was diese Welt braucht.\n\nDie Sonne steht für Authentizität. Sie fragt dich nicht, was du sein solltest, sondern erinnert dich an das, was du schon immer warst. In Momenten, in denen du ganz bei dir bist -- wenn du lachst, ohne dich zu zügeln, wenn du erschaffst, ohne dich zu hinterfragen, wenn du liebst, ohne dich zu schützen -- dann lebst du deine Sonnenenergie. Es sind die Augenblicke, in denen du aufhörst zu funktionieren und anfängst zu sein.\n\nDeine Sonne schenkt dir auch Großzügigkeit. Wie das Gestirn am Himmel, das alles gleichmäßig wärmt, trägst du eine natürliche Güte in dir, die andere anzieht. Menschen spüren dein Licht, auch wenn du es selbst nicht siehst. Vertraue darauf: Alles, was du brauchst, um zu strahlen, ist bereits in dir angelegt. Du musst nichts hinzufügen. Du musst nur den Mut finden, die Schleier abzulegen.',
    botschaft:
      'Ich, die Sonne, spreche zu dir aus dem Zentrum deines Seins. Ich bin das Licht, das du in dir trägst, seit dem ersten Atemzug. Ich habe dich gewärmt, als du dachtest, du seist allein. Ich habe in dir gebrannt, als die Welt kalt war. Du brauchst mich nicht zu suchen -- ich bin bereits da, in jedem Herzschlag, in jedem Moment des Mutes, in jedem Lächeln, das du verschenkst. Erlaube dir, so hell zu strahlen, wie du wirklich bist. Die Welt hat auf genau dein Licht gewartet.',
    ritual:
      'Stehe bei Sonnenaufgang auf und stelle dich mit geschlossenen Augen der aufgehenden Sonne entgegen. Lege beide Hände auf dein Herz. Atme siebenmal tief ein und aus, und spüre mit jedem Atemzug, wie goldenes Licht dein Herz durchflutet. Sprich leise: "Ich erlaube mir zu strahlen." Halte diesen Moment fünf Minuten lang. Praktiziere dieses Ritual an drei aufeinanderfolgenden Morgen, um deine Sonnenkraft zu aktivieren.',
  },
  mond: {
    id: 'mond',
    name: 'Mond',
    symbol: '☽',
    energie: 'Emotion, Intuition und innere Welt',
    beschreibung:
      'Der Mond ist der sanfte Hüter deiner inneren Landschaft -- jenes weiten, stillen Ozeans in dir, der sich unter der Oberfläche deines Alltags erstreckt. Während die Welt dein äußeres Gesicht kennt, kennt der Mond dein wahres: das verletzliche, das sehnsüchtige, das träumende. Er ist der Teil in dir, der nachts wach liegt und Fragen stellt, die das Tageslicht nicht zu stellen wagt.\n\nDie Mondenergie in dir ist zutiefst weiblich -- und das unabhängig davon, welchem Geschlecht du dich zugehörig fühlst. Sie ist die empfangende Kraft, die fühlt, bevor sie denkt, die weiß, bevor sie versteht. Hast du schon einmal einen Raum betreten und sofort gespürt, dass etwas nicht stimmt, obwohl alle lächelten? Das war dein Mond, der unter die Oberfläche blickte, dorthin, wo die Wahrheit lebt.\n\nPsychologisch steht der Mond für dein inneres Kind und deine frühesten emotionalen Prägungen. Er speichert die Erinnerungen an Geborgenheit und Verlassenheit, an Wärme und Kälte, an die ersten Berührungen und die ersten Tränen. Diese Erinnerungen formen, wie du heute liebst, wie du dich schützt, wie du dich öffnest. Der Mond in deinem Seelen-Profil zeigt dir nicht nur, was du fühlst, sondern warum du so fühlst, wie du fühlst.\n\nWie der sichtbare Mond am Himmel durchläufst auch du innere Zyklen. Es gibt Zeiten der Fülle, in denen dein Herz überströmt vor Dankbarkeit und Verbundenheit. Und es gibt Zeiten der Leere, der Dunkelheit, des Rückzugs. Beide gehören zu dir. Der Mond lehrt dich, dass Dunkelheit nicht das Gegenteil von Licht ist, sondern sein notwendiger Ruhepol. Ohne die dunkle Mondnacht gäbe es den silbernen Glanz des Vollmonds nicht.\n\nDeine Intuition ist die Sprache des Mondes. Sie spricht nicht in Worten, sondern in Bildern, Gefühlen, Ahnungen und Träumen. Je mehr du lernst, dieser leisen Stimme zu vertrauen, desto tiefer wird deine Verbindung zu dir selbst und zu den Menschen, die du liebst. Der Mond lädt dich ein, nicht alles verstehen zu müssen. Manchmal reicht es, einfach zu fühlen. Manchmal ist das Fühlen die höchste Form des Verstehens.',
    botschaft:
      'Ich, der Mond, spreche zu dir aus der Stille deiner Nacht. Ich bin der silberne Faden, der dich mit deinem Innersten verbindet -- mit allem, was du fühlst und nicht in Worte fassen kannst. Ich bin da, wenn du weinst und nicht weißt warum. Ich bin da, wenn du träumst und die Wahrheit klarer siehst als je am Tag. Vertraue deinen Gefühlen, denn sie sind keine Schwäche. Sie sind deine tiefste Weisheit, dein ältestes Wissen. Lass dich von mir halten.',
    ritual:
      'Setze dich bei Vollmond an ein Fenster oder gehe nach draußen. Halte eine Schale mit Wasser in deinen Händen und lasse das Mondlicht hineinfallen. Schließe die Augen und frage leise: "Was will in mir gesehen werden?" Lausche fünf bis zehn Minuten, ohne nach einer Antwort zu suchen. Trinke danach einen Schluck des Mondwassers. Schreibe anschließend auf, was dir in den Sinn kam -- ohne zu bewerten.',
  },
  merkur: {
    id: 'merkur',
    name: 'Merkur',
    symbol: '☿',
    energie: 'Kommunikation, Verstand und Wandelbarkeit',
    beschreibung:
      'Merkur ist der flinke Bote zwischen den Welten -- jene quicklebendige Kraft in dir, die Brücken baut zwischen dem, was du denkst, und dem, was du sagst, zwischen dem, was du weißt, und dem, was du verstehst. Er ist der Wind deines Geistes, der niemals stillsteht, sondern ständig neue Verbindungen knüpft, neue Muster erkennt, neue Wege findet.\n\nWenn du nachts wach liegst und deine Gedanken rasen, dann ist das Merkur, der arbeitet. Wenn dir unter der Dusche die genialste Idee kommt, dann ist das Merkur, der spielt. Er ist die Stimme in dir, die Fragen stellt, die andere nicht einmal denken. Er ist die Neugier, die dich antreibt, hinter jede Tür zu schauen, jedes Buch aufzuschlagen, jedes Gespräch zu suchen.\n\nDoch Merkur ist weit mehr als nur Intellekt. In der antiken Mythologie war Hermes -- sein griechisches Pendant -- der Gott der Schwellen und Übergänge, der Wanderer zwischen Himmel und Unterwelt. Diese Grenzgänger-Energie trägst auch du in dir. Du hast die Gabe, zwischen verschiedenen Welten zu vermitteln: zwischen Kopf und Herz, zwischen Logik und Intuition, zwischen deiner Innenwelt und der äußeren Realität.\n\nPsychologisch betrachtet repräsentiert Merkur deine Art zu lernen und die Welt zu begreifen. Bist du jemand, der durch Worte versteht, durch Gespräche und Geschichten? Oder begreifst du die Welt durch Beobachtung, durch stille Analyse, durch das Erkennen verborgener Zusammenhänge? Merkur zeigt dir, wie dein einzigartiger Geist funktioniert -- und wie du ihn am besten nährst.\n\nDie Wandelbarkeit des Merkur ist seine größte Stärke und gleichzeitig seine größte Herausforderung. Er kann sich jeder Situation anpassen, jede Sprache lernen, jede Perspektive einnehmen. Doch manchmal verlierst du dich dabei in der Vielfalt der Möglichkeiten. Dann erinnert dich Merkur daran: Du musst nicht alles gleichzeitig sein. Wähle einen Gedanken, einen Weg, ein Wort -- und gib ihm deine volle Aufmerksamkeit. Denn die wahre Magie des Geistes liegt nicht in seiner Geschwindigkeit, sondern in seiner Tiefe.',
    botschaft:
      'Ich, Merkur, spreche zu dir in der Sprache zwischen den Worten. Ich bin die Funkenflut deiner Gedanken, das Tanzen deiner Synapsen, die Freude am Verstehen. Du denkst, du hättest zu viele Gedanken? Nein -- du hast einen Geist, der lebendig ist, der fliegt, der Verbindungen sieht, wo andere nur Chaos erkennen. Ehre dieses Geschenk. Dein Verstand ist kein Werkzeug, das du kontrollieren musst. Er ist ein lebendiger Strom. Lerne, auf seinen Wellen zu reiten, statt gegen sie zu schwimmen.',
    ritual:
      'Nimm dir jeden Mittwoch -- dem Tag des Merkur -- zwanzig Minuten für freies Schreiben. Setze dich mit einem leeren Blatt hin und schreibe alles auf, was kommt, ohne Punkt und Komma, ohne Korrektur. Lass deinen Geist fließen. Nach zwanzig Minuten lies das Geschriebene einmal laut vor. Unterstreiche die drei Sätze, die dich am meisten berühren. Sie tragen eine Botschaft für deine Woche.',
  },
  venus: {
    id: 'venus',
    name: 'Venus',
    symbol: '♀',
    energie: 'Liebe, Schönheit und Harmonie',
    beschreibung:
      'Venus ist die Göttin in deinem kosmischen Bauplan -- jene uralte, weise Kraft, die weiß, dass Schönheit nicht Luxus ist, sondern Nahrung für die Seele. Sie ist der Teil in dir, der sich nach Berührung sehnt, nach Verbindung, nach dem Gefühl, gesehen und geliebt zu werden, genau so, wie du bist. Venus fragt nicht, ob du es verdienst, geliebt zu werden. Für sie ist das keine Frage. Es ist eine Tatsache.\n\nIn einer Welt, die Leistung über Liebe stellt, ist Venus deine innere Rebellin. Sie flüstert dir zu: Du darfst genießen. Du darfst dich an der Schönheit einer Blüte erfreuen, an der Wärme einer Umarmung, am Geschmack deines Lieblingsessens. Du darfst schöne Dinge besitzen und schöne Momente erschaffen, ohne dich dafür zu rechtfertigen. Denn Schönheit ist nicht oberflächlich -- sie ist ein Tor zur Seele.\n\nPsychologisch verkörpert Venus deine Beziehungsmuster und dein Wertesystem. Sie zeigt dir, wie du liebst und wie du geliebt werden möchtest. Sie offenbart, was du wirklich wertschätzt -- nicht, was die Gesellschaft dir als wertvoll verkauft, sondern was dein Herz zum Klingen bringt. Vielleicht ist es Kunst. Vielleicht ist es ein tiefes Gespräch bei Kerzenlicht. Vielleicht ist es der stille Moment, wenn du allein in der Natur stehst und die Welt so vollkommen erscheint, dass dir die Tränen kommen.\n\nVenus regiert auch dein Selbstwertgefühl -- jenes zarte Pflänzchen, das so leicht zertreten wird und doch immer wieder nachwächst. Wenn du dich unwürdig fühlst, wenn du dich klein machst, wenn du gibst und gibst und vergisst, auch zu empfangen, dann ist es Venus, die sanft an deine Schulter tippt und sagt: Du bist nicht hier, um dich aufzuopfern. Du bist hier, um zu blühen.\n\nDie Harmonie, die Venus sucht, ist keine Konfliktvermeidung. Es ist die tiefe Erkenntnis, dass alles miteinander verbunden ist, dass Geben und Nehmen ein Tanz sind, dass wahre Schönheit in der Balance liegt. Lass Venus dich lehren, dass du es wert bist -- nicht weil du etwas geleistet hast, sondern weil du existierst.',
    botschaft:
      'Ich, Venus, spreche zu dir aus dem Garten deines Herzens. Ich bin die Rose, die in dir blüht, auch wenn du glaubst, es sei Winter. Ich bin die Sehnsucht nach Zärtlichkeit, die du manchmal unterdrückst, weil du gelernt hast, stark zu sein. Aber höre mich: Deine Weichheit ist deine größte Stärke. Dein Verlangen nach Schönheit ist keine Schwäche, sondern dein Kompass. Folge dem, was dein Herz zum Singen bringt. Erlaube dir, zu empfangen. Die Liebe, die du suchst, sucht auch dich.',
    ritual:
      'Bereite dir an einem Freitagabend -- dem Tag der Venus -- ein Bad mit Rosenblüten oder Rosenöl. Zünde eine rosa oder grüne Kerze an. Während du im Wasser liegst, lege eine Hand auf dein Herz und sprich: "Ich bin es wert, geliebt zu werden. Ich öffne mich für die Schönheit des Lebens." Bleibe mindestens zwanzig Minuten im Wasser. Spüre, wie Venus dein Herz wärmt und dein Selbstwertgefühl nährt.',
  },
  mars: {
    id: 'mars',
    name: 'Mars',
    symbol: '♂',
    energie: 'Willenskraft, Energie und Durchsetzung',
    beschreibung:
      'Mars ist das Feuer in deinem Blut, der Krieger in deiner Seele, die Urkraft, die dich morgens aus dem Bett treibt und flüstert: Heute kämpfe ich für das, was mir wichtig ist. Er ist nicht die blinde Aggression, die zerstört -- er ist die gerichtete Kraft, die erschafft. Mars ist der Schmied, der das Eisen deines Willens im Feuer der Leidenschaft formt.\n\nIn einer Gesellschaft, die uns oft beibringt, unsere Wut zu unterdrücken und unsere Kraft zu zähmen, ist Mars eine unbequeme Energie. Doch ohne ihn wärst du ein Blatt im Wind, getrieben von den Wünschen anderer, unfähig, Nein zu sagen, unfähig, für dich einzustehen. Mars gibt dir das Rückgrat, das du brauchst, um aufrecht durch das Leben zu gehen. Er ist die Stimme in dir, die sagt: Das akzeptiere ich nicht. Das verdiene ich nicht. Ich gehe meinen eigenen Weg.\n\nPsychologisch betrachtet repräsentiert Mars deine Durchsetzungsfähigkeit und dein Verhältnis zu Konflikten. Wie gehst du mit Wut um? Schluckst du sie herunter, bis sie dich von innen auffrisst? Oder lässt du sie heraus wie einen Vulkan, unkontrolliert und verheerend? Mars in seiner höchsten Ausdrucksform lehrt dich den mittleren Weg: deine Kraft bewusst einzusetzen, deine Grenzen klar zu setzen, deine Leidenschaft zu kanalisieren, ohne andere dabei zu verletzen.\n\nMars ist auch die Energie der Sexualität und der körperlichen Vitalität. Er erinnert dich daran, dass du nicht nur Geist und Seele bist, sondern auch Körper. Ein Körper, der bewegt werden will, der schwitzt und atmet und lebt. Wenn du dich träge und antriebslos fühlst, wenn du das Gefühl hast, auf der Stelle zu treten, dann ist es oft Mars, der nach Ausdruck verlangt. Gib ihm Raum: Bewege dich, tanze, laufe, kämpfe -- im übertragenen und im wörtlichen Sinne.\n\nDie wahre Lektion des Mars ist diese: Stärke und Sanftheit schließen sich nicht aus. Der größte Krieger ist nicht der, der am lautesten schreit, sondern der, der weiß, wann er kämpfen muss und wann er sein Schwert niederlegen darf. Mars schenkt dir die Kraft, mutig zu sein -- und Mut bedeutet manchmal, sich verletzlich zu zeigen.',
    botschaft:
      'Ich, Mars, spreche zu dir aus dem Feuer deines Willens. Ich bin die Glut, die unter deiner Oberfläche brennt, die Kraft, die dich antreibt, auch wenn du müde bist. Du hast gelernt, brav zu sein, leise zu sein, dich anzupassen. Aber ich sage dir: In dir lebt ein Krieger, eine Kriegerin, die größer ist als jede Angst. Deine Wut ist heilig, wenn du sie richtig nutzt. Dein Feuer ist ein Geschenk. Stehe auf, richte dich auf, und gehe den Weg, der wirklich deiner ist.',
    ritual:
      'Gehe an einem Dienstagmorgen -- dem Tag des Mars -- nach draußen und bewege dich kraftvoll für mindestens fünfzehn Minuten. Laufe, springe, mache Liegestütze, tanze wild -- was auch immer deinem Körper entspricht. Spüre das Feuer in deinen Muskeln. Danach stehe still, die Fäuste leicht geballt, und sprich dreimal laut: "Ich bin stark. Ich setze mich durch. Ich stehe zu mir." Spüre die Kraft in deinem ganzen Körper.',
  },
  jupiter: {
    id: 'jupiter',
    name: 'Jupiter',
    symbol: '♃',
    energie: 'Expansion, Glück und Weisheit',
    beschreibung:
      'Jupiter ist der König der Planeten, und seine Energie in dir ist königlich im wahrsten Sinne: großzügig, weitherzlich, voll tiefer Zuversicht, dass das Universum es gut mit dir meint. Wenn du jemals das Gefühl hattest, dass das Leben dich trägt, dass zur richtigen Zeit die richtigen Türen aufgehen, dass Fülle kein Zufall ist, sondern ein Grundprinzip des Kosmos -- dann hast du Jupiter in dir gespürt.\n\nJupiter ist der große Lehrer und Philosoph des Tierkreises. Doch er lehrt nicht durch Strenge wie Saturn, sondern durch Begeisterung. Er zeigt dir die Welt in ihrer ganzen Pracht und flüstert: Siehst du, wie wunderbar das alles ist? Siehst du, wie viel es noch zu entdecken gibt? Jupiter weckt in dir den Forschergeist, die Reiselust, den Hunger nach Erkenntnis. Er ist der Grund, warum du manchmal mitten in der Nacht ein Buch aufschlägst oder ein Flugticket buchst oder ein Gespräch mit einem Fremden beginnst.\n\nPsychologisch steht Jupiter für dein Vertrauen in das Leben und deinen Sinn für Bedeutung. Er fragt: Woran glaubst du? Was gibt deinem Dasein Sinn? Diese Fragen klingen groß, und das sind sie auch. Jupiter schreckt nicht vor großen Fragen zurück. Er ist die Kraft in dir, die über den Tellerrand schaut, die das große Ganze sieht, die versteht, dass dein persönliches Schicksal eingebettet ist in etwas viel Größeres.\n\nDoch Jupiter hat auch seinen Schatten. Wer alles haben will, verliert manchmal das Wesentliche aus den Augen. Wer immer nach dem Horizont strebt, übersieht die Schönheit zu seinen Füßen. Jupiter kann dich dazu verleiten, zu viel zu versprechen, zu viel zu erwarten, zu schnell zu wachsen. Die reife Jupiterenergie weiß: Wahre Fülle ist nicht die Anhäufung von allem, sondern die tiefe Wertschätzung dessen, was bereits da ist.\n\nJupiter schenkt dir auch die Gabe des Glaubens -- nicht unbedingt im religiösen Sinne, sondern jenes tiefe Urvertrauen, dass du getragen bist. Dass die Dinge sich fügen. Dass selbst in der dunkelsten Stunde ein Licht wartet, das dich führt. Dieses Vertrauen ist vielleicht das größte Geschenk, das Jupiter dir macht. Bewahre es wie einen Schatz.',
    botschaft:
      'Ich, Jupiter, spreche zu dir aus der Weite des Kosmos. Ich bin die Stimme, die sagt: Es darf leicht sein. Es darf gut werden. Es darf sogar besser werden, als du es dir vorstellst. Du neigst dazu, dein Glück kleinzureden, deine Erfolge zu relativieren, deine Träume zu beschneiden. Aber ich sage dir: Das Universum kennt keine Obergrenze für dein Glück. Erlaube dir, groß zu träumen. Erlaube dir, zu empfangen. Du bist nicht hier, um gerade so durchzukommen. Du bist hier, um zu blühen.',
    ritual:
      'Zünde an einem Donnerstag -- dem Tag des Jupiter -- eine violette oder dunkelblaue Kerze an. Nimm ein Blatt Papier und schreibe zwölf Dinge auf, für die du dankbar bist. Dann schreibe drei große Wünsche auf, ohne sie zu zensieren. Falte das Papier, lege es unter die Kerze und sprich: "Ich öffne mich für die Fülle des Universums." Lass die Kerze mindestens eine Stunde brennen, während du in Stille sitzt oder meditierst.',
  },
  saturn: {
    id: 'saturn',
    name: 'Saturn',
    symbol: '♄',
    energie: 'Struktur, Disziplin und Reife',
    beschreibung:
      'Saturn ist der Planet, vor dem viele Menschen Angst haben -- und genau das macht ihn so mächtig. Er ist der strenge Lehrmeister, der alte Weise, der dich nicht tröstet, wenn du fällst, sondern dir die Hand reicht und sagt: Steh auf. Du bist stärker, als du denkst. Und dann zeigt er dir, dass er recht hat.\n\nSaturn kommt nicht mit Geschenken. Er kommt mit Prüfungen. Doch jede Prüfung, die er dir auferlegt, ist eine Einladung, zu wachsen, zu reifen, zu dem Menschen zu werden, der du sein kannst, wenn du aufhörst, vor dir selbst wegzulaufen. Saturn fragt dich: Was bist du bereit, für deine Träume zu tun? Wie viel Disziplin bringst du auf? Wie viel Geduld? Denn Saturn weiß, was viele nicht wahrhaben wollen: Die schönsten Dinge im Leben brauchen Zeit.\n\nPsychologisch repräsentiert Saturn dein inneres Gerüst -- die Strukturen, die dir Halt geben, die Grenzen, die dich schützen, die Werte, die dich verankern. Ohne Saturn wärst du formlos, ein Ozean ohne Ufer. Er gibt deinem Leben Kontur. Er lehrt dich, Verantwortung zu übernehmen, nicht als Last, sondern als Ausdruck deiner Reife. Denn Verantwortung zu tragen bedeutet, zu sagen: Ich bin erwachsen genug, um die Konsequenzen meiner Entscheidungen zu tragen.\n\nSaturn steht auch für die Wunden deiner Vergangenheit -- die Narben, die dich geformt haben. Die Enttäuschungen, die dich gelehrt haben, vorsichtig zu sein. Die Verluste, die dich gelehrt haben, was wirklich zählt. Saturn vergoldet keine Schmerzen. Er sagt dir ehrlich: Ja, das war schwer. Ja, das hat wehgetan. Aber schau, was es aus dir gemacht hat. Schau, welche Stärke aus deiner Verwundung gewachsen ist.\n\nDie höchste Ausdrucksform des Saturn ist die Meisterschaft. Nicht die Perfektion, die sich nie zufrieden gibt, sondern die gelassene Souveränität eines Menschen, der seine Grenzen kennt und gerade deshalb frei ist. Saturn lehrt dich, dass wahre Freiheit nicht die Abwesenheit von Regeln ist, sondern die bewusste Wahl, welchen Regeln du folgst. Er ist der härteste und gleichzeitig der treueste Begleiter auf deinem Weg. Denn anders als Jupiter, der kommt und geht, bleibt Saturn. Er bleibt, bis du die Lektion gelernt hast. Und dann -- erst dann -- lässt er los.',
    botschaft:
      'Ich, Saturn, spreche zu dir aus der Tiefe der Zeit. Ich weiß, du empfindest mich oft als Last, als den Planeten, der dir Steine in den Weg legt. Aber jeder Stein, den ich dir gegeben habe, war ein Baustein. Schau zurück und sieh: Du hast aus meinen Prüfungen eine Festung gebaut. Deine Stärke ist kein Zufall -- sie ist das Ergebnis von allem, was du durchgestanden hast. Ich bin stolz auf dich. Und ich sage dir: Die Meisterschaft, die du suchst, ist näher, als du denkst.',
    ritual:
      'Wähle einen Samstagabend -- den Tag des Saturn -- für dieses Ritual der Struktur. Setze dich an einen aufgeräumten Tisch mit einer schwarzen oder dunkelbraunen Kerze. Schreibe drei Verpflichtungen auf, die du dir selbst gegenüber eingehst. Formuliere sie klar und konkret. Lies sie laut vor und sprich: "Ich übernehme Verantwortung für mein Leben." Bewahre das Blatt an einem Ort auf, an dem du es täglich siehst. Wiederhole das Ritual einmal im Monat.',
  },
  uranus: {
    id: 'uranus',
    name: 'Uranus',
    symbol: '♅',
    energie: 'Freiheit, Innovation und Umbruch',
    beschreibung:
      'Uranus ist der kosmische Blitz -- jene Kraft, die ohne Vorwarnung einschlägt und alles verändert. Er ist der Revolutionär unter den Planeten, der Rebell, der Visionär. Wenn du jemals das Gefühl hattest, dass du nicht in die Welt passt, die man dir vorgesetzt hat, wenn du schon als Kind gespürt hast, dass die Dinge auch ganz anders sein könnten -- dann hast du die Uranusenergie in dir erkannt.\n\nUranus duldet keine Käfige. Nicht die äußeren, die die Gesellschaft dir baut, und schon gar nicht die inneren, die du dir selbst errichtest. Er ist die Stimme in dir, die sagt: Das reicht mir nicht. Da muss doch mehr sein. Lass mich raus. Und wenn du dieser Stimme folgst, geschehen die erstaunlichsten Dinge. Plötzliche Wendungen, unerwartete Begegnungen, Geistesblitze, die dein ganzes Leben auf den Kopf stellen können.\n\nPsychologisch repräsentiert Uranus deinen Individuationsprozess -- den lebenslangen Weg, auf dem du dich von den Erwartungen anderer befreist und zu dem Menschen wirst, der du wirklich bist. Das ist nicht immer bequem. Uranus macht es dir nicht leicht, denn er fordert echte Freiheit, und echte Freiheit bedeutet, auch die Sicherheit des Vertrauten loszulassen. Den Job, der bequem war, aber deine Seele erstickte. Die Beziehung, die funktionierte, aber dein Herz nicht berührte. Die Überzeugungen, die dir Halt gaben, aber nicht mehr wahr waren.\n\nDoch Uranus zerstört nicht um der Zerstörung willen. Er bricht auf, damit Neues wachsen kann. Er ist wie der Blitz, der den alten Baum spaltet und gleichzeitig den Boden mit Stickstoff nährt, damit neue Samen keimen können. Jeder Umbruch, den Uranus in dein Leben bringt, trägt den Keim einer höheren Ordnung in sich.\n\nUranus schenkt dir auch die Gabe der Originalität. Du denkst nicht wie alle anderen, du siehst nicht wie alle anderen, du fühlst nicht wie alle anderen -- und das ist kein Fehler. Es ist deine Superkraft. Die Welt braucht keine weitere Kopie. Sie braucht dein Original. Uranus erinnert dich daran, dass Anpassung überbewertet wird und dass die Menschen, die die Welt verändert haben, immer die waren, die sich weigerten, so zu sein wie alle anderen.',
    botschaft:
      'Ich, Uranus, spreche zu dir wie ein Blitz aus heiterem Himmel. Ich bin die Unruhe in dir, die nicht aufhört, auch wenn du versuchst, sie zu ignorieren. Ich bin der Funke, der überspringt, wenn du anfängst, dein eigenes Denken in Frage zu stellen. Du hast Angst vor Veränderung? Gut. Das bedeutet, dass die Veränderung groß genug ist, um wichtig zu sein. Springe. Das Netz erscheint erst, wenn du springst. Deine Einzigartigkeit ist kein Problem, das gelöst werden muss. Sie ist die Lösung.',
    ritual:
      'Wähle einen Tag, an dem du etwas tust, das du noch nie getan hast. Es kann klein sein: einen anderen Weg zur Arbeit nehmen, ein Gericht kochen, das du nicht kennst, ein Gespräch mit einem Fremden beginnen. Das Entscheidende ist der Bruch mit der Routine. Schreibe abends auf, was du erlebt hast und wie es sich angefühlt hat. Praktiziere dieses Ritual der Erneuerung einmal pro Woche, um deine Uranusenergie lebendig zu halten.',
  },
  neptun: {
    id: 'neptun',
    name: 'Neptun',
    symbol: '♆',
    energie: 'Traum, Spiritualität und Auflösung',
    beschreibung:
      'Neptun ist der Ozean hinter dem Ozean -- jene unendliche Tiefe in dir, die sich nicht greifen, nicht messen, nicht in Worte fassen lässt. Er ist der Nebel, der die scharfen Kanten der Realität weich zeichnet und dich daran erinnert, dass hinter allem Sichtbaren etwas Unsichtbares wartet, das ebenso real ist. Neptun ist die Sehnsucht deiner Seele nach dem Göttlichen, nach dem Ewigen, nach dem Gefühl, Teil von etwas zu sein, das größer ist als du selbst.\n\nWenn du jemals vor einem Sonnenuntergang standest und Tränen kamen, ohne dass du wusstest warum. Wenn du jemals Musik gehört hast, die dich an einen Ort trug, den du nie besucht hast und doch wiedererkanntest. Wenn du jemals das Gefühl hattest, dass die Grenzen deines Körpers sich auflösen und du eins wirst mit allem -- dann hast du Neptun berührt. Oder besser: Er hat dich berührt.\n\nPsychologisch steht Neptun für dein Unbewusstes in seiner tiefsten Schicht -- dort, wo persönliche Erinnerungen sich auflösen in kollektive Bilder, Archetypen und Mythen. Er ist die Quelle deiner Kreativität, deiner Träume, deiner Visionen. Künstler, Musiker, Dichter und Heiler tragen oft eine starke Neptunenergie in sich, denn sie haben Zugang zu jenem Raum, in dem Inspiration geboren wird -- jenem Raum, der keiner Logik gehorcht und doch die tiefsten Wahrheiten enthält.\n\nDoch Neptun hat auch seinen Schleier der Illusion. Er kann dich dazu verleiten, die Realität zu meiden, dich in Tagträumen zu verlieren, in Süchten oder in der Sehnsucht nach einer perfekten Welt, die es nicht gibt. Die reife Neptunenergie lernt, zwischen Inspiration und Flucht zu unterscheiden. Sie lehrt dich, mit beiden Füßen auf der Erde zu stehen und gleichzeitig den Himmel zu berühren.\n\nNeptun schenkt dir das tiefste aller Geschenke: Mitgefühl. Nicht das Mitleid, das von oben herab schaut, sondern das wahre Mitfühlen, das die Grenzen zwischen Ich und Du auflöst. Wenn du den Schmerz eines anderen Menschen so tief spürst, als wäre er dein eigener, dann ist Neptun in dir aktiv. Diese Empathie ist sowohl deine größte Gabe als auch deine größte Verwundbarkeit. Lerne, sie zu tragen, ohne daran zu zerbrechen.',
    botschaft:
      'Ich, Neptun, spreche zu dir aus der Tiefe des Ozeans deiner Seele. Ich bin das Flüstern, das du hörst, wenn alles still wird. Ich bin der Traum, den du nicht vergessen kannst, obwohl du ihn nicht verstehst. Du fragst dich manchmal, ob du zu sensibel bist für diese Welt. Ich sage dir: Du bist nicht zu sensibel. Du bist genau richtig durchlässig, damit das Licht des Göttlichen durch dich hindurchscheinen kann. Deine Sehnsucht ist dein Kompass. Folge ihr. Sie führt dich nach Hause.',
    ritual:
      'Schaffe dir einen stillen Raum, am besten in der Abenddämmerung. Zünde eine weiße oder silberne Kerze an und lass leise, meditative Musik laufen. Schließe die Augen und stelle dir vor, du stehst an einem unendlichen Ozean unter einem Sternenhimmel. Atme langsam und tief. Lass alle Gedanken kommen und gehen wie Wellen. Bleibe zwanzig Minuten in dieser Stille. Schreibe danach einen Traum oder ein Bild auf, das dir erschienen ist.',
  },
  pluto: {
    id: 'pluto',
    name: 'Pluto',
    symbol: '♇',
    energie: 'Transformation, Macht und Erneuerung',
    beschreibung:
      'Pluto ist die mächtigste und gleichzeitig am meisten gefürchtete Kraft in deinem kosmischen Bauplan. Er ist der Herrscher der Unterwelt, der Hüter der Schwelle zwischen Tod und Wiedergeburt -- und damit meine ich nicht den physischen Tod, sondern jene kleinen und großen Tode, die du im Laufe deines Lebens stirbst. Jedes Mal, wenn eine alte Version von dir sterben musste, damit eine neue geboren werden konnte -- das war Pluto. Jedes Mal, wenn du durch eine Krise gingst und dich am anderen Ende als ein anderer Mensch wiederfandest -- das war Pluto.\n\nPluto arbeitet im Verborgenen. Er gräbt tief, dorthin, wo du nicht hinschauen willst. In die Keller deiner Psyche, in die Schubladen, die du verschlossen hast, in die Erinnerungen, die du begraben hast. Er tut das nicht aus Grausamkeit, sondern aus Liebe -- einer Liebe, die so radikal ist, dass sie alles zerstört, was nicht authentisch ist. Pluto ist der kosmische Chirurg, der das Kranke herausschneidet, damit das Gesunde heilen kann.\n\nPsychologisch repräsentiert Pluto deine tiefsten Machtthemen: Kontrolle und Loslassen, Ohnmacht und Ermächtigung, Zerstörung und Schöpfung. Er zeigt dir, wo du Macht über andere ausübst und wo andere Macht über dich haben. Er konfrontiert dich mit deinen dunkelsten Ängsten und deinen geheimsten Wünschen. Und er tut das alles mit einer Intensität, die keine Halbwahrheiten duldet.\n\nDoch Pluto ist nicht nur Zerstörung. Er ist der Phönix, der aus der Asche steigt. Jeder Tod, den er dir schenkt, ist eine Wiedergeburt. Jede Krise, die er dir bringt, trägt den Samen einer tieferen Wahrheit in sich. Wenn du dich jemals gefragt hast, woher deine unglaubliche Widerstandskraft kommt, deine Fähigkeit, immer wieder aufzustehen, egal wie oft das Leben dich niedergeworfen hat -- dann danke Pluto. Er hat dich nicht gebrochen. Er hat dich geschmiedet.\n\nDie höchste Plutokraft ist die bewusste Transformation -- die Entscheidung, das, was nicht mehr dient, loszulassen, nicht weil man es muss, sondern weil man bereit ist, etwas Größeres zu empfangen. In diesem Moment wird aus dem gefürchteten Zerstörer der weiseste Heiler. Pluto lehrt dich die tiefste aller Wahrheiten: Am Ende jeder Dunkelheit wartet nicht das Nichts, sondern ein Licht, das heller strahlt als alles, was du je gekannt hast.',
    botschaft:
      'Ich, Pluto, spreche zu dir aus der Tiefe deiner Seele, dort, wo kein Licht hinreicht und doch alles beginnt. Ich bin die Kraft, die du fürchtest und die dich gleichzeitig am Leben hält. Jede Narbe, die du trägst, ist ein Beweis meiner Arbeit -- und ein Zeichen deiner Stärke. Du bist nicht zerbrochen. Du bist transformiert worden. Und die Transformation ist noch nicht vorbei. Was du jetzt loslassen musst, weißt du bereits. Du brauchst nur den Mut, die Hand zu öffnen. Was danach kommt, wird dich erstaunen.',
    ritual:
      'Wähle eine Nacht bei abnehmendem Mond. Schreibe auf ein Blatt Papier alles, was du loslassen möchtest: alte Schmerzen, Überzeugungen, Beziehungsmuster, Ängste. Lies alles einmal laut vor. Dann verbrenne das Papier sicher in einer feuerfesten Schale. Während es brennt, sprich: "Ich lasse los, was mich nicht mehr dient. Ich mache Raum für meine Wiedergeburt." Verstreue die Asche am nächsten Morgen in der Natur.',
  },
};

// ---------------------------------------------------------------------------
// Helper
// ---------------------------------------------------------------------------

/**
 * Get a planet by its key.
 * Throws if the key is not found.
 */
export function getPlanet(id: string): PlanetInfo {
  const planet = planeten[id];
  if (!planet) {
    throw new Error(`Planet with id "${id}" not found`);
  }
  return planet;
}
