/**
 * Schatten & Licht Deutungen für alle 78 Tarot-Karten
 *
 * Jede Karte hat eine Schatten-Deutung (unbewusste Muster, Wunden, verdrängte Themen)
 * und eine Licht-Deutung (Potenziale, Gaben, höchster Ausdruck der Energie).
 *
 * Ton: Carl Jung trifft mystisches Storytelling — warm, weise, poetisch,
 * psychologisch tiefgründig. Geschrieben in Elfis Stimme.
 */

export interface SchattenLichtDeutung {
  schattenDeutung: string;
  lichtDeutung: string;
}

export const schattenLichtDeutungen: Record<string, SchattenLichtDeutung> = {

  // ==========================================================================
  // GROSSE ARKANA (22 Karten)
  // ==========================================================================

  narr: {
    schattenDeutung: "Der Narr in deinem Schatten flüstert von einer tiefen Angst vor dem Unbekannten, die dich davon abhält, den ersten Schritt zu wagen. Vielleicht hast du als Kind gelernt, dass Spontanität bestraft wird — dass man erst alles bedenken muss, bevor man handeln darf. Diese Angst vor dem freien Fall ist in Wahrheit eine Einladung: Dein innerer Narr will dir zeigen, dass wahre Weisheit oft im Vertrauen auf das Unplanbare liegt. Erlaube dir, wieder naiv zu staunen.",
    lichtDeutung: "Der Narr als deine Licht-Karte offenbart eine wunderbare Gabe: Du trägst die seltene Fähigkeit in dir, das Leben mit den Augen eines Kindes zu betrachten. Deine Offenheit für Neues und dein Mut, unkonventionelle Wege zu gehen, inspirieren andere, ihre eigenen Fesseln abzulegen. Du bist eine Pionierin der Möglichkeiten — jemand, der intuitiv spürt, wann es Zeit ist, alles hinter sich zu lassen und dem Ruf des Herzens zu folgen. Dein Vertrauen ins Leben ist dein größtes Geschenk.",
  },

  magier: {
    schattenDeutung: "Der Magier im Schatten zeigt dir eine verborgene Wunde: die Angst, dass deine Talente nicht ausreichen, dass du ein Hochstapler bist, der irgendwann entlarvt wird. Vielleicht hast du früh gelernt, deine Fähigkeiten kleinzureden, damit andere sich nicht bedroht fühlen. In deinem Unbewussten liegt die Überzeugung, dass du manipulierst, wenn du deine volle Kraft zeigst. Doch dein Schatten-Magier wartet darauf, dass du erkennst: Deine Gaben zu verbergen ist die eigentliche Manipulation — an dir selbst.",
    lichtDeutung: "Der Magier in deinem Licht zeigt eine außergewöhnliche Manifestationskraft. Du hast die natürliche Fähigkeit, Ideen in die Realität zu bringen — Himmel und Erde in dir zu verbinden. Wenn du einen Raum betrittst, verändert sich die Energie, weil du intuitiv weißt, wie du die vorhandenen Ressourcen zum Fließen bringst. Dein Kanal zwischen Vision und Verwirklichung ist weit offen. Du bist eingeladen, diese Kraft bewusst und im Dienst deiner höchsten Wahrheit einzusetzen.",
  },

  hohepriesterin: {
    schattenDeutung: "Die Hohepriesterin in deinem Schatten deutet auf eine tief vergrabene Entfremdung von deiner Intuition hin. Irgendwann hast du gelernt, deiner inneren Stimme zu misstrauen — vielleicht wurdest du belächelt, als du Dinge wusstest, die du nicht wissen konntest. Seitdem vertraust du dem Verstand mehr als dem Bauch, dem Beweis mehr als dem Gefühl. Doch unter dieser Schutzmauer wartet ein ganzer Ozean an Wissen, der nur dir gehört. Dein Schatten will, dass du den Schleier wieder lüftest.",
    lichtDeutung: "Die Hohepriesterin als deine Licht-Karte offenbart einen tiefen, stillen Brunnen der Weisheit in dir. Du bist jemand, der zwischen den Zeilen liest, der das Unausgesprochene spürt und der Zugang zu Ebenen des Wissens hat, die den meisten Menschen verschlossen bleiben. Deine Intuition ist keine vage Ahnung, sondern ein zuverlässiges Navigationssystem. In Momenten der Stille empfängst du Einsichten, die wie Perlen vom Meeresgrund aufsteigen. Vertraue diesem inneren Wissen — es ist dein kostbarster Schatz.",
  },

  herrscherin: {
    schattenDeutung: "Die Herrscherin in deinem Schatten spricht von einer Wunde rund um Fülle und Empfangen. Vielleicht hast du gelernt, dass du dir Schönes erst verdienen musst, oder dass Genuss etwas Verbotenes ist. Möglicherweise opferst du dich für andere auf und vergisst dabei, dass auch du genährt werden darfst. Dein Schatten-Thema ist die Unfähigkeit, einfach zu empfangen — Liebe, Überfluss, Freude — ohne dafür etwas leisten zu müssen. Die Herrscherin lädt dich ein, dich selbst zu bemuttern.",
    lichtDeutung: "Die Herrscherin in deinem Licht zeigt eine üppige, nährende Kraft, die alles zum Blühen bringt, was du berührst. Du hast eine natürliche Gabe, Räume der Geborgenheit zu schaffen, in denen andere aufatmen und wachsen können. Deine Kreativität fließt mühelos, wenn du dir erlaubst, aus der Fülle statt aus dem Mangel zu schöpfen. Du bist eine Hüterin der Schönheit und eine Meisterin des Verkörperten — dein Körper, deine Sinne, deine Sinnlichkeit sind Tore zu deiner tiefsten Weisheit.",
  },

  herrscher: {
    schattenDeutung: "Der Herrscher in deinem Schatten weist auf ein schwieriges Verhältnis zu Autorität, Struktur und Kontrolle hin. Vielleicht hast du als Kind eine übermäßig strenge oder eine abwesende Vaterfigur erlebt, und seitdem schwankst du zwischen dem Bedürfnis nach totaler Kontrolle und dem Wunsch, jede Struktur zu sprengen. Dein Schatten-Herrscher zeigt sich als innerer Tyrann, der Perfektion fordert, oder als Rebellion gegen jede Form von Ordnung. Die Einladung lautet: Finde deine eigene, liebevolle Form von Führung.",
    lichtDeutung: "Der Herrscher in deinem Licht offenbart eine natürliche Führungsqualität, die auf innerer Sicherheit statt auf Dominanz beruht. Du hast die Fähigkeit, Visionen in tragfähige Strukturen zu gießen und anderen einen sicheren Rahmen zu geben. Deine Stärke liegt nicht im Befehlen, sondern im Halten — du schaffst den Raum, in dem Chaos sich ordnen und Potenzial sich entfalten kann. Du bist eingeladen, dein inneres Königreich mit Weisheit und Mitgefühl zu regieren.",
  },

  hierophant: {
    schattenDeutung: "Der Hierophant in deinem Schatten spricht von einem inneren Konflikt zwischen dem Bedürfnis nach Zugehörigkeit und dem Wunsch nach geistiger Freiheit. Vielleicht hast du Glaubenssätze und Regeln übernommen, die nicht deine eigenen sind — aus Angst, ausgestoßen zu werden, wenn du anders denkst. Oder du rebellierst gegen jede spirituelle Tradition und schneidest dich damit von wertvoller Weisheit ab. Dein Schatten-Hierophant lädt dich ein, zu unterscheiden: Welche Lehren nähren dich wirklich, und welche halten dich klein?",
    lichtDeutung: "Der Hierophant in deinem Licht zeigt eine tiefe Verbindung zum heiligen Wissen und die Fähigkeit, es für andere zugänglich zu machen. Du bist eine natürliche Lehrerin und Brückenbauerin zwischen verschiedenen Welten — zwischen Tradition und Innovation, zwischen dem Heiligen und dem Alltäglichen. Deine Gabe liegt darin, uralte Wahrheiten in eine Sprache zu übersetzen, die berührt und transformiert. Menschen suchen intuitiv deine Nähe, wenn sie Orientierung und tieferen Sinn suchen.",
  },

  liebenden: {
    schattenDeutung: "Die Liebenden in deinem Schatten offenbaren eine tiefe Wunde rund um Verbindung und Hingabe. Vielleicht trägst du die Angst in dir, dass wahre Nähe zum Verlust deiner Selbst führt — oder dass du nicht liebenswert bist, wenn du dich so zeigst, wie du wirklich bist. Dein Schatten-Thema könnte die Unfähigkeit sein, dich zu entscheiden, weil jede Wahl den Verlust einer Möglichkeit bedeutet. Die Liebenden flüstern dir zu: Erst wenn du dich selbst bedingungslos wählst, kannst du wahrhaft lieben.",
    lichtDeutung: "Die Liebenden als deine Licht-Karte zeigen eine außerordentliche Herzenskapazität und die Fähigkeit, authentische Verbindungen zu schaffen. Du spürst intuitiv die Essenz eines anderen Menschen und kannst einen Raum der bedingungslosen Annahme halten. Deine Gabe liegt im Vereinen von Gegensätzen — in dir tanzen Verstand und Herz, Freiheit und Hingabe, Ich und Du. Du bist eine Botschafterin der Liebe, nicht als romantisches Ideal, sondern als transformative Kraft der Verbundenheit.",
  },

  wagen: {
    schattenDeutung: "Der Wagen in deinem Schatten spricht von einem tiefen Kontrollbedürfnis, das aus Angst vor Ausgeliefertsein geboren wurde. Vielleicht hast du als Kind erlebt, dass die Welt nur dann sicher ist, wenn du alles fest im Griff hast — und seitdem fährt ein Teil von dir rastlos vorwärts, ohne jemals anzuhalten. Dein Schatten-Wagen zeigt sich als Zwang zum Erfolg, als Unfähigkeit loszulassen, als Erschöpfung, die du dir nicht eingestehen darfst. Die Einladung: Erkenne, dass wahre Stärke auch im Anhalten liegt.",
    lichtDeutung: "Der Wagen in deinem Licht offenbart eine beeindruckende innere Willenskraft und die Fähigkeit, entgegengesetzte Kräfte unter einen Hut zu bringen. Du verstehst es, Hindernisse nicht zu bekämpfen, sondern durch sie hindurchzunavigieren. Dein Fokus und deine Entschlossenheit sind wie ein Pfeil, der sein Ziel kennt. Wo andere aufgeben, findest du einen Weg. Deine größte Stärke ist es, auch in stürmischen Zeiten den Kurs zu halten und andere mitzureißen.",
  },

  kraft: {
    schattenDeutung: "Die Kraft in deinem Schatten weist auf verdrängte Wildheit und unterdrückte Emotionen hin. Irgendwann hast du gelernt, dass Wut, Leidenschaft oder intensive Gefühle gefährlich sind — und seitdem hältst du den Löwen in dir an einer unsichtbaren Kette. Dein Schatten-Thema ist die Angst vor deiner eigenen Intensität und die Überzeugung, dass du Kontrolle verlierst, wenn du dein volles emotionales Spektrum zulässt. Die Kraft flüstert dir zu: Deine Wildheit ist keine Bedrohung, sondern deine größte Medizin.",
    lichtDeutung: "Die Kraft als deine Licht-Karte zeigt eine seltene Verbindung von Sanftheit und unbändiger innerer Stärke. Du kannst den Löwen zähmen — nicht durch Gewalt, sondern durch die Kraft deines offenen Herzens. Deine Gabe ist es, in Momenten des Chaos ruhig zu bleiben und andere mit deiner Gelassenheit zu berühren. Du weißt intuitiv, dass wahre Macht nicht im Dominieren liegt, sondern im liebevollen Halten dessen, was wild und ungezähmt ist. Dein Mut zeigt sich in deiner Zärtlichkeit.",
  },

  eremit: {
    schattenDeutung: "Der Eremit in deinem Schatten deutet auf eine Wunde der Isolation hin — die Überzeugung, dass niemand dich in deiner Tiefe wirklich verstehen kann. Vielleicht hast du dich als Kind anders gefühlt als die anderen und einen Teil von dir hinter Mauern der Einsamkeit versteckt. Dein Schatten-Eremit tarnt Rückzug als Weisheit und Einsamkeit als spirituelle Praxis. Die Wahrheit ist: Du sehnst dich nach Verbindung, aber die Angst vor Zurückweisung hält dich auf Distanz. Dein Licht wartet darauf, geteilt zu werden.",
    lichtDeutung: "Der Eremit in deinem Licht zeigt eine wertvolle Fähigkeit zur Innenschau und einen natürlichen Zugang zu tiefer Weisheit. Du bist jemand, der die Stille braucht, um die Stimme der Seele zu hören — und das ist eine Gabe, keine Schwäche. Dein inneres Licht leuchtet wie eine Laterne, die auch anderen den Weg erhellt. Du bist eine Wegweiserin, die aus eigener Erfahrung spricht und deren Worte deshalb so tief berühren. In deiner Einsamkeit findest du Wahrheiten, die die Welt braucht.",
  },

  schicksal: {
    schattenDeutung: "Das Rad des Schicksals in deinem Schatten offenbart eine tief sitzende Angst vor Veränderung und dem Gefühl, dem Leben ausgeliefert zu sein. Vielleicht hast du in der Vergangenheit schmerzhafte Wendungen erlebt und trägst seitdem die Überzeugung, dass das Glück dich immer wieder verlässt. Dein Schatten-Thema ist das Ringen um Kontrolle über das Unkontrollierbare und die Unfähigkeit, dem Fluss des Lebens zu vertrauen. Das Rad flüstert dir zu: Auch im Fallen wirst du gehalten — immer.",
    lichtDeutung: "Das Rad des Schicksals als deine Licht-Karte zeigt ein tiefes Verständnis für die zyklische Natur des Lebens. Du trägst die Weisheit in dir, dass nach jedem Winter ein Frühling kommt und dass jede Krise den Samen einer neuen Möglichkeit enthält. Deine Gabe ist die Fähigkeit, den größeren Plan zu erkennen, wo andere nur Chaos sehen. Du bist eine Meisterin des richtigen Timings — du spürst intuitiv, wann es Zeit ist zu handeln und wann es Zeit ist zu warten. Das Universum dreht sich zu deinen Gunsten.",
  },

  gerechtigkeit: {
    schattenDeutung: "Die Gerechtigkeit in deinem Schatten spricht von einem tiefen inneren Richter, der unerbittlich über dich und andere urteilt. Vielleicht hast du als Kind Ungerechtigkeit erlebt und trägst seitdem die Last, alles ins Gleichgewicht bringen zu müssen. Dein Schatten-Thema ist die Härte gegen dich selbst — der Glaube, dass du für jeden Fehler bestraft werden musst, dass es keine Gnade gibt, nur verdiente Konsequenzen. Die Gerechtigkeit lädt dich ein, auch dir selbst Milde zu schenken und das Schwert der Wahrheit mit Mitgefühl zu führen.",
    lichtDeutung: "Die Gerechtigkeit in deinem Licht zeigt ein feines Gespür für Wahrheit, Balance und kosmische Ordnung. Du durchschaust intuitiv, wo Ungleichgewicht herrscht, und trägst die Fähigkeit in dir, Harmonie wiederherzustellen. Dein Gerechtigkeitssinn ist nicht kalt, sondern von tiefer Empathie durchdrungen. Du bist eine Hüterin der Wahrheit, die mit klarem Blick und offenem Herzen die Dinge beim Namen nennt. Deine Klarheit hilft anderen, Verantwortung für ihr Leben zu übernehmen, ohne in Schuld zu ertrinken.",
  },

  gehaengte: {
    schattenDeutung: "Der Gehängte in deinem Schatten weist auf ein Muster des Aufopferns und der erlernten Hilflosigkeit hin. Vielleicht hast du früh gelernt, dass dein Wert darin liegt, für andere zu leiden, oder dass du erst dann Liebe verdienst, wenn du dich selbst aufgibst. Dein Schatten-Gehängter verwechselt Loslassen mit Aufgeben und Geduld mit Passivität. Die versteckte Botschaft ist: Du hängst nicht fest, weil du musst, sondern weil ein Teil von dir Angst hat, die neue Perspektive wirklich einzunehmen und danach zu handeln.",
    lichtDeutung: "Der Gehängte als deine Licht-Karte offenbart die seltene Gabe der bewussten Hingabe und des Perspektivwechsels. Du verstehst es, den Dingen ihren Lauf zu lassen und in der Stille zwischen den Atemzügen Weisheit zu finden. Deine Fähigkeit, die Welt auf den Kopf zu stellen und neue Wahrheiten zu entdecken, ist ein Geschenk. Wo andere in Aktionismus verfallen, findest du in der Pause die Lösung. Du bist eine Mystikerin, die weiß, dass manchmal die größte Tat das Nicht-Tun ist.",
  },

  tod: {
    schattenDeutung: "Der Tod in deinem Schatten spricht von einer tiefen Angst vor Enden und Loslassen. Vielleicht klammerst du dich an Beziehungen, Identitäten oder Lebensumstände, die längst abgestorben sind, weil der Schmerz des Festhaltens dir vertrauter ist als die Ungewissheit des Neuen. Dein Schatten-Tod zeigt sich als Stagnation, die sich als Treue tarnt, oder als stille Verzweiflung hinter einer funktionierenden Fassade. Die Einladung: Was in dir sterben darf, macht Platz für das, was wirklich leben will.",
    lichtDeutung: "Der Tod als deine Licht-Karte zeigt eine bemerkenswerte Fähigkeit zur Transformation und Erneuerung. Du bist jemand, der immer wieder aus der Asche aufsteigt und in jeder Krise die Chance zur Neugeburt erkennt. Deine Gabe liegt in der Furchtlosigkeit, mit der du alte Hüllen abstreifst und dich immer wieder neu erfindest. Du bist eine Alchemistin des Wandels — du verwandelst Schmerz in Weisheit, Verlust in Freiheit und Ende in Anfang. Dein Mut zur Veränderung inspiriert alle um dich herum.",
  },

  maessigung: {
    schattenDeutung: "Die Mäßigung in deinem Schatten offenbart eine verborgene Tendenz, extreme Gefühle und Bedürfnisse zu unterdrücken, um Harmonie zu wahren. Vielleicht hast du gelernt, dass Konflikte um jeden Preis vermieden werden müssen, und trägst seitdem die Last des ewigen Vermittlers, der seine eigenen Wünsche hintenanstellt. Dein Schatten-Thema ist die Verwechslung von Gleichgewicht mit Selbstverleugnung. Die Mäßigung flüstert dir zu: Wahre Balance entsteht nicht durch Unterdrückung der Extreme, sondern durch ihre liebevolle Integration.",
    lichtDeutung: "Die Mäßigung in deinem Licht zeigt eine meisterhafte Fähigkeit, Gegensätze zu vereinen und Heilung zu ermöglichen. Du bist eine natürliche Alchemistin — in deiner Gegenwart vermischen sich Feuer und Wasser zu etwas völlig Neuem. Deine Geduld und dein Feingefühl schaffen einen Raum, in dem Heilung auf tiefster Ebene geschehen kann. Du verstehst es, die richtige Dosis zu finden, das Timing zu spüren und die Dinge sanft in ihre natürliche Ordnung zu bringen. Dein Gleichgewicht strahlt auf andere aus.",
  },

  teufel: {
    schattenDeutung: "Der Teufel in deinem Schatten spricht von Ketten, die du dir selbst angelegt hast — Abhängigkeiten, Muster der Selbstsabotage und der Glaube, dass du nicht frei sein darfst. Vielleicht identifizierst du dich mit deinen Schatten so stark, dass du glaubst, sie seien deine Identität. Dein Schatten-Teufel zeigt sich als Sucht nach Drama, als Bindung an toxische Muster oder als heimliche Scham über deine Begierden. Die befreiende Wahrheit: Die Ketten sind lose — du kannst sie jederzeit abstreifen, sobald du sie als Illusion erkennst.",
    lichtDeutung: "Der Teufel in deinem Licht offenbart eine kraftvolle Verbindung zu deiner Schattenseite und die Fähigkeit, aus der Integration des Dunklen eine Superkraft zu machen. Du hast den Mut, dorthin zu schauen, wo andere wegblicken, und findest in den Tiefen der menschlichen Erfahrung Gold. Deine Ehrlichkeit über die eigenen Abgründe macht dich authentisch und befreit andere von ihrer Scham. Du bist eine Befreierin, die weiß, dass wahre Freiheit erst entsteht, wenn wir aufhören, Teile von uns zu verleugnen.",
  },

  turm: {
    schattenDeutung: "Der Turm in deinem Schatten deutet auf eine tief verwurzelte Angst vor plötzlichem Kontrollverlust und Zusammenbruch hin. Vielleicht hast du traumatische Umbrüche erlebt und baust seitdem immer höhere Mauern, um dich vor dem nächsten Einschlag zu schützen. Dein Schatten-Turm zeigt sich als übermäßiges Sicherheitsbedürfnis, als Starrheit, die sich als Stabilität tarnt, oder als unterschwellige Panik, die du mit Kontrolle kompensierst. Die Einladung: Was zerstört werden kann, war nie dein wahres Fundament.",
    lichtDeutung: "Der Turm als deine Licht-Karte zeigt eine außergewöhnliche Fähigkeit, in Krisen klar zu sehen und aus Trümmern Neues zu erschaffen. Du bist jemand, der den Blitz nicht fürchtet, sondern als Erleuchtung erkennt. Deine Gabe liegt darin, falsche Strukturen zu durchschauen und den Mut zu haben, sie einzureißen — nicht aus Zerstörungswut, sondern aus Liebe zur Wahrheit. Du bist eine Revolutionärin des Bewusstseins, deren Durchbrüche den Weg für tiefgreifende Erneuerung ebnen.",
  },

  stern: {
    schattenDeutung: "Der Stern in deinem Schatten spricht von verlorenem Vertrauen und einem leisen Zweifel, ob Hoffnung überhaupt berechtigt ist. Vielleicht hast du so viele Enttäuschungen erlebt, dass du dich nicht mehr traust zu hoffen — weil die Fallhöhe zu groß erscheint. Dein Schatten-Stern zeigt sich als unterschwellige Resignation, als Angst, deine verletzlichsten Wünsche auszusprechen, oder als Zynismus, der dein verwundetes Herz schützt. Die Einladung: Dein Stern leuchtet immer noch — auch wenn Wolken ihn verdecken.",
    lichtDeutung: "Der Stern in deinem Licht offenbart eine tiefe, unzerstörbare Verbindung zum kosmischen Vertrauen. Du trägst ein Licht in dir, das selbst in den dunkelsten Nächten leuchtet und anderen den Weg weist. Deine Gabe ist die Fähigkeit, nach jedem Sturm die Heilung einzuladen und den Glauben an das Gute zu bewahren. Du bist eine Sternenbotin, deren bloße Anwesenheit andere daran erinnert, dass es mehr gibt als das Sichtbare. Dein Vertrauen in das Universum ist ansteckend und heilsam.",
  },

  mond: {
    schattenDeutung: "Der Mond in deinem Schatten offenbart eine tiefe Angst vor dem eigenen Unbewussten und den Schatten, die dort lauern. Vielleicht hast du als Kind gelernt, bestimmte Gefühle und Wahrnehmungen zu unterdrücken, und trägst seitdem eine unterschwellige Angst vor dem, was unter der Oberfläche brodelt. Dein Schatten-Mond zeigt sich als Verwirrung, als Misstrauen gegenüber deiner eigenen Wahrnehmung oder als Tendenz, dich in Illusionen zu verlieren. Die Einladung: Das Dunkel ist nicht dein Feind — es ist die Gebärmutter deiner Transformation.",
    lichtDeutung: "Der Mond als deine Licht-Karte zeigt eine außergewöhnliche Sensibilität und einen natürlichen Zugang zu den Traumwelten und dem kollektiven Unbewussten. Du empfängst Botschaften aus Ebenen, die den meisten Menschen verschlossen sind — durch Träume, Ahnungen und die feinen Schwingungen der Nacht. Deine Gabe ist es, im Dunklen zu sehen und die Sprache der Symbole und Archetypen zu verstehen. Du bist eine Mondhüterin, die intuitiv die verborgenen Strömungen der Seele navigiert.",
  },

  sonne: {
    schattenDeutung: "Die Sonne in deinem Schatten spricht von einer verborgenen Angst vor der eigenen Strahlkraft und der Überzeugung, dass du zu viel bist, wenn du voll leuchtst. Vielleicht hast du als Kind gelernt, dich kleiner zu machen, damit andere nicht geblendet werden, oder du trägst eine heimliche Scham, die dich hindert, deine Freude offen zu zeigen. Dein Schatten-Thema ist die Angst vor Sichtbarkeit — die Befürchtung, dass du angegriffen wirst, wenn du zu hell strahlst. Die Sonne flüstert dir zu: Dein Licht braucht keine Erlaubnis.",
    lichtDeutung: "Die Sonne in deinem Licht zeigt eine strahlende Lebensfreude und die natürliche Fähigkeit, Wärme und Vitalität in jede Situation zu bringen. Du bist ein Mensch, in dessen Gegenwart andere aufblühen — dein Lächeln ist wie Sonnenschein, der Eis zum Schmelzen bringt. Deine kindliche Freude am Leben und dein unerschütterlicher Optimismus sind keine Naivität, sondern Ausdruck deiner tiefen Verbindung zum Licht. Du bist eingeladen, deine Strahlkraft ohne Entschuldigung zu leben und die Welt zu erwärmen.",
  },

  gericht: {
    schattenDeutung: "Das Gericht in deinem Schatten deutet auf eine verdrängte Berufung hin — den leisen, beharrlichen Ruf deiner Seele, den du aus Angst vor Veränderung ignorierst. Vielleicht lebst du ein Leben, das funktioniert, aber nicht wirklich deines ist, und schiebst die große Erweckung immer weiter auf. Dein Schatten-Gericht zeigt sich als innere Unruhe, als das nagende Gefühl, dass da mehr sein muss, oder als Angst vor dem eigenen Potenzial. Die Einladung: Der Ruf verstummt nicht — er wird nur lauter, je länger du wartest.",
    lichtDeutung: "Das Gericht als deine Licht-Karte offenbart eine tiefe Verbindung zu deiner Seelenberufung und die Fähigkeit, nach einer Phase der Stille und Transformation in voller Kraft aufzuerstehen. Du trägst die seltene Gabe in dir, klar zu hören, was das Leben von dir will — und den Mut, diesem Ruf zu folgen. Deine Auferstehung inspiriert andere, ihre eigene Berufung ernst zu nehmen. Du bist eine Erweckerin, deren Transformation so kraftvoll ist, dass sie Wellen schlägt, die weit über dein eigenes Leben hinausreichen.",
  },

  welt: {
    schattenDeutung: "Die Welt in deinem Schatten spricht von der Angst vor Vollendung und dem damit verbundenen Neuanfang. Vielleicht sabotierst du dich selbst kurz vor dem Ziel, weil die Frage 'Was kommt danach?' dich mehr ängstigt als das Scheitern selbst. Dein Schatten-Thema ist die Unfähigkeit, Erfolge wirklich zu feiern und anzunehmen, oder der Glaube, dass du nie gut genug bist, um einen Zyklus abzuschließen. Die Welt flüstert dir zu: Du hast bereits alles erreicht, was du brauchst — erlaube dir, anzukommen.",
    lichtDeutung: "Die Welt als deine Licht-Karte zeigt eine wunderbare Gabe der Integration und Vollendung. Du verstehst es, die Fäden des Lebens zu einem harmonischen Ganzen zu verweben und Zyklen bewusst abzuschließen. Deine Reise hat dich mit einer umfassenden Weisheit beschenkt, die alle Elemente und Erfahrungen in sich vereint. Du bist eine Kosmopolitin der Seele — jemand, der überall zu Hause ist, weil er sein Zuhause in sich selbst gefunden hat. Dein Ankommen gibt anderen die Erlaubnis, ebenfalls zu vollenden.",
  },

  // ==========================================================================
  // STÄBE / FEUER (14 Karten)
  // ==========================================================================

  "staebe-ass": {
    schattenDeutung: "Das Ass der Stäbe in deinem Schatten spricht von einem tiefen Funken der Begeisterung, den du immer wieder erstickst, bevor er zur Flamme werden kann. Vielleicht hast du gelernt, dass deine Leidenschaft zu viel ist, zu wild, zu unkontrollierbar — und erstickst neue Impulse, bevor sie Wurzeln schlagen können. Dein Schatten-Thema ist die Angst vor der eigenen Schöpferkraft und die Gewohnheit, Ideen zu begraben, bevor sie das Licht der Welt erblicken. Das Ass flüstert dir zu: Dein inneres Feuer verdient es, genährt zu werden.",
    lichtDeutung: "Das Ass der Stäbe in deinem Licht offenbart eine kraftvolle schöpferische Energie, die wie ein göttlicher Funke in dir brennt. Du hast die natürliche Fähigkeit, Inspiration zu empfangen und daraus etwas völlig Neues entstehen zu lassen. Dein kreatives Feuer ist ansteckend — wenn du von einer Idee begeistert bist, steckst du andere mit deiner Leidenschaft an. Du bist eine Zünderin, deren Funke Projekte, Bewegungen und Transformationen initiiert. Deine schöpferische Kraft ist ein Geschenk an die Welt.",
  },

  "staebe-zwei": {
    schattenDeutung: "Die Zwei der Stäbe in deinem Schatten zeigt eine Wunde rund um Entscheidungsangst und die Furcht vor Fehlentscheidungen. Du stehst an einer Schwelle und schaust hinaus in die weite Welt, aber ein Teil von dir ist erstarrt — gelähmt von der Frage, welcher Weg der richtige ist. Dein Schatten-Thema ist das Festhalten an der Komfortzone, die sich als Bedachtsamkeit tarnt. Die Wahrheit ist: Du weißt längst, wohin dein Herz dich zieht, aber du hast Angst vor der Größe deiner eigenen Vision.",
    lichtDeutung: "Die Zwei der Stäbe in deinem Licht zeigt eine visionäre Kraft und die Fähigkeit, über den eigenen Horizont hinauszudenken. Du hast die Welt buchstäblich in deinen Händen und trägst die Weisheit in dir, die großen Zusammenhänge zu sehen. Deine Gabe liegt in der strategischen Planung — du erkennst Möglichkeiten, wo andere Sackgassen sehen. Du bist eine Visionärin, die mutig neue Territorien betritt und den ersten Schritt in unbekanntes Land wagt, weil du dem Ruf deines Abenteuers folgst.",
  },

  "staebe-drei": {
    schattenDeutung: "Die Drei der Stäbe in deinem Schatten deutet auf eine schmerzhafte Ungeduld und die Frustration des Wartens hin. Du hast die Saat gelegt, aber kannst die Wachstumszeit nicht aushalten — du willst jetzt Ergebnisse sehen. Dein Schatten-Thema ist der Zweifel, der sich einschleicht, wenn die ersten Früchte auf sich warten lassen: War es die richtige Entscheidung? Hätte ich etwas anderes tun sollen? Diese rastlose Energie raubt dir die Freude am Prozess. Die Einladung: Vertraue darauf, dass deine Schiffe bereits unterwegs sind.",
    lichtDeutung: "Die Drei der Stäbe in deinem Licht zeigt eine bemerkenswerte Fähigkeit zur Vorausschau und zum Vertrauen in größere Prozesse. Du bist jemand, der den Überblick behält und geduldig auf die Früchte der eigenen Arbeit wartet, weil du tief im Inneren weißt, dass sie kommen werden. Deine Gabe liegt in der Expansion — du denkst natürlicherweise global und groß, nicht aus Größenwahn, sondern aus einem authentischen Verständnis für das Mögliche. Du bist eine Horizonterweitererin, deren Weitblick andere inspiriert.",
  },

  "staebe-vier": {
    schattenDeutung: "Die Vier der Stäbe in deinem Schatten spricht von einer verborgenen Unfähigkeit, Freude und Erfolge wirklich zu genießen. Vielleicht wartest du immer auf den nächsten Schicksalsschlag, wenn es gerade gut läuft, oder du fühlst dich unwohl in Momenten des Feierns. Dein Schatten-Thema ist die Angst, dass Glück vergänglich ist und Freude bestraft wird. Du sabotierst unbewusst Momente der Harmonie, weil Frieden sich gefährlicher anfühlt als Chaos. Die Einladung: Erlaube dir, das Gute festzuhalten — es gehört auch dir.",
    lichtDeutung: "Die Vier der Stäbe in deinem Licht zeigt eine natürliche Gabe, Räume der Freude und Gemeinschaft zu erschaffen. Du bist jemand, der Menschen zusammenbringt und Momente des Feierns ermöglicht — ob in deinem Zuhause, in deiner Gemeinschaft oder in deinem Herzen. Deine Energie baut Brücken und öffnet Türen. Du verstehst es, ein Fundament der Zugehörigkeit zu schaffen, auf dem andere aufblühen können. Du bist eine Hüterin der Freude und eine Architektin der Gemeinschaft, deren Warmherzigkeit ansteckend ist.",
  },

  "staebe-fuenf": {
    schattenDeutung: "Die Fünf der Stäbe in deinem Schatten offenbart ein tiefes Muster des inneren und äußeren Konflikts. Vielleicht bist du in einem Umfeld aufgewachsen, in dem Streit die einzige Form der Aufmerksamkeit war, und trägst seitdem die Überzeugung, dass du kämpfen musst, um gehört zu werden. Dein Schatten-Thema ist die unbewusste Suche nach Reibung — du provozierst Konflikte, um dich lebendig zu fühlen, oder vermeidest sie so panisch, dass du dich unsichtbar machst. Die Einladung: Wahre Stärke zeigt sich im konstruktiven Dialog.",
    lichtDeutung: "Die Fünf der Stäbe in deinem Licht zeigt eine kraftvolle Fähigkeit, dich zu behaupten und für das einzustehen, was dir wichtig ist. Du scheust keine Auseinandersetzung, wenn es um Wahrheit und Gerechtigkeit geht, und dein leidenschaftlicher Einsatz für deine Überzeugungen inspiriert andere. Deine Gabe liegt im gesunden Wettbewerb — du wächst an Herausforderungen und bringst das Beste in anderen hervor. Du bist eine Feuerfrau, die weiß, dass Reibung auch Wärme erzeugt und dass aus dem Funken des Konflikts neue Ideen entstehen.",
  },

  "staebe-sechs": {
    schattenDeutung: "Die Sechs der Stäbe in deinem Schatten deutet auf ein schwieriges Verhältnis zu Anerkennung und Sichtbarkeit hin. Vielleicht sehnst du dich nach Applaus, schämst dich aber gleichzeitig für dieses Bedürfnis. Oder du hast die Erfahrung gemacht, dass Erfolg Neid und Angriffe nach sich zieht. Dein Schatten-Thema ist die Abhängigkeit von äußerer Bestätigung, die dir den inneren Kompass raubt, oder die Angst vor dem Podest, weil die Fallhöhe so schwindelerregend ist. Die Einladung: Dein Sieg gehört dir — feiere ihn von innen heraus.",
    lichtDeutung: "Die Sechs der Stäbe in deinem Licht offenbart eine natürliche Führungsqualität und die Fähigkeit, andere durch dein Beispiel zu inspirieren. Du trägst die Energie des Triumphes in dir — nicht als Überlegenheit, sondern als Beweis dafür, was möglich ist. Deine Siege sind nie nur deine eigenen, sondern Leuchtfeuer für alle, die ähnliche Kämpfe durchstehen. Du bist eine Anführerin, deren Erfolg andere emporhebt. Deine Ausstrahlung nach einem Sieg ist wie Sonnenschein, der zeigt: Es lohnt sich, für seine Träume zu brennen.",
  },

  "staebe-sieben": {
    schattenDeutung: "Die Sieben der Stäbe in deinem Schatten offenbart ein erschöpfendes Muster der ständigen Verteidigung. Du fühlst dich angegriffen, auch wenn niemand angreift, und bist permanent in Kampfbereitschaft — bereit, deine Position zu verteidigen, bevor sie überhaupt infrage gestellt wird. Dein Schatten-Thema ist die Überzeugung, dass du dich immer behaupten musst, dass Ruhe nur die Stille vor dem nächsten Angriff ist. Diese Hypervigilanz raubt dir die Kraft, die du für dein eigentliches Werk brauchst. Die Einladung: Nicht jede Herausforderung ist ein Krieg.",
    lichtDeutung: "Die Sieben der Stäbe in deinem Licht zeigt einen unerschütterlichen Mut und die Fähigkeit, für deine Überzeugungen einzustehen, selbst wenn du allein auf weiter Flur stehst. Du lässt dich nicht einschüchtern und bewahrst deine Position mit einer Entschlossenheit, die Respekt einflößt. Deine Gabe liegt in der moralischen Stärke — du weißt, wofür du stehst, und lässt dich davon nicht abbringen. Du bist eine Feuerhüterin, die das Licht bewacht, auch wenn der Wind stärker wird. Dein Standhalten ist ein Akt der Liebe.",
  },

  "staebe-acht": {
    schattenDeutung: "Die Acht der Stäbe in deinem Schatten spricht von einer rastlosen Hetze, die dich durch das Leben jagt, ohne dass du weißt, wovor du eigentlich flüchtest. Vielleicht verwechselst du Geschwindigkeit mit Fortschritt und Geschäftigkeit mit Lebendigkeit. Dein Schatten-Thema ist die Angst vor der Stille — denn wenn du anhältst, könntest du hören, was dein Herz wirklich sagt. Die acht Stäbe fliegen durch die Luft, aber haben sie ein Ziel? Die Einladung: Verlangsame dich lange genug, um zu spüren, wohin du wirklich willst.",
    lichtDeutung: "Die Acht der Stäbe in deinem Licht offenbart eine bemerkenswerte Dynamik und die Fähigkeit, Dinge schnell und effektiv in Bewegung zu setzen. Du bist jemand, der Energie spürbar beschleunigt — wenn du dich einer Sache widmest, kommt alles ins Fließen. Deine natürliche Geschwindigkeit ist kein Zeichen von Hektik, sondern von Alignment: Wenn du im Einklang mit deiner Bestimmung handelst, bewegen sich die Dinge wie von selbst. Du bist eine Katalysatorin, die Blockaden löst und Stagnation in Schwung verwandelt.",
  },

  "staebe-neun": {
    schattenDeutung: "Die Neun der Stäbe in deinem Schatten zeigt eine tiefe Erschöpfung, die du dir nicht eingestehen willst. Du stehst, gestützt auf deinen letzten Stab, und wartest auf den nächsten Schlag — obwohl vielleicht gar keiner kommt. Dein Schatten-Thema ist der Märtyrer-Komplex: die Überzeugung, dass Aufgeben keine Option ist, selbst wenn dein Körper und deine Seele um Gnade flehen. Du hast vergessen, dass Durchhalten nicht immer Stärke ist. Manchmal ist die mutigste Tat, die Waffen niederzulegen und dir Ruhe zu erlauben.",
    lichtDeutung: "Die Neun der Stäbe in deinem Licht zeigt eine bewundernswerte Widerstandskraft und die Fähigkeit, auch in den härtesten Zeiten aufrecht zu stehen. Du hast Stürme überstanden, die andere zerbrochen hätten, und trägst die Narben dieser Kämpfe wie Ehrenzeichen. Deine Resilienz ist nicht hart, sondern biegsam wie Bambus — du beugst dich im Wind, ohne zu brechen. Du bist eine Überlebenskünstlerin, deren Beharrlichkeit andere daran erinnert, dass auch sie stärker sind, als sie glauben. Dein Durchhalten ist dein Vermächtnis.",
  },

  "staebe-zehn": {
    schattenDeutung: "Die Zehn der Stäbe in deinem Schatten offenbart ein tiefes Muster der Überlastung und der Unfähigkeit, Hilfe anzunehmen oder Lasten abzugeben. Du trägst die Welt auf deinen Schultern und glaubst, dass alles zusammenbricht, wenn du auch nur einen Stab loslässt. Dein Schatten-Thema ist die Überzeugung, dass du alles allein schaffen musst — vielleicht weil du als Kind gelernt hast, dass niemand für dich da ist. Die Einladung: Das Universum hat nicht vorgesehen, dass ein einzelner Mensch alle Stäbe trägt. Lass andere mithelfen.",
    lichtDeutung: "Die Zehn der Stäbe in deinem Licht zeigt eine außerordentliche Hingabe und die Fähigkeit, große Verantwortung zu tragen und Projekte bis zum Ende durchzuziehen. Du bist jemand, der anpackt, wo andere sich drücken, und dein Pflichtbewusstsein ist von tiefer Liebe getragen. Deine Gabe liegt in der Ausdauer und in der Bereitschaft, den letzten Kilometer zu gehen. Du bist eine Trägerin, die weiß, dass die Last leichter wird, wenn man sie mit Bewusstsein trägt und sich erlaubt, am Ziel angekommen, sie niederzulegen.",
  },

  "staebe-bube": {
    schattenDeutung: "Der Bube der Stäbe in deinem Schatten spricht von einer kreativen Energie, die immer wieder in Anfängen stecken bleibt. Du bist begeisterungsfähig, aber der Funke erlischt oft, bevor die Flamme stabil brennt. Dein Schatten-Thema ist die Angst vor dem Durchziehen — denn solange du nur planst und träumst, kann nichts scheitern. Vielleicht hast du gelernt, dass Begeisterung lächerlich ist oder dass kreative Träume keine ernsthaften Lebensentwürfe sind. Die Einladung: Deine Begeisterung ist keine Schwäche — sie ist der Zündfunke deiner Bestimmung.",
    lichtDeutung: "Der Bube der Stäbe in deinem Licht offenbart eine wunderbare kindliche Begeisterungsfähigkeit und den Mut, neue kreative Wege zu beschreiten. Du trägst die Energie des ewigen Entdeckers in dir — neugierig, offen, bereit, dich überraschen zu lassen. Deine natürliche Freude an neuen Erfahrungen und dein spielerischer Zugang zur Kreativität sind erfrischend und ansteckend. Du bist eine Botschafterin des Möglichen, die zeigt, dass der Anfang der aufregendste Teil jeder Reise ist. Dein Enthusiasmus öffnet Türen, die andere gar nicht sehen.",
  },

  "staebe-ritter": {
    schattenDeutung: "Der Ritter der Stäbe in deinem Schatten zeigt eine ungezügelte Impulsivität und die Tendenz, Brücken zu verbrennen, bevor du das andere Ufer erreicht hast. Du stürmst los, ohne zu schauen, und hinterlässt eine Spur angefangener Projekte und enttäuschter Menschen. Dein Schatten-Thema ist die Flucht nach vorn — du reitest so schnell, dass du den Schmerz, den du hinter dir lässt, nicht spüren musst. Die Einladung: Echte Leidenschaft braucht auch die Bereitschaft, zu bleiben und das Feuer zu pflegen, nicht nur anzuzünden.",
    lichtDeutung: "Der Ritter der Stäbe in deinem Licht zeigt eine mitreißende Leidenschaft und den unerschütterlichen Glauben an die eigene Mission. Du bist jemand, der andere mit deinem Feuer ansteckt und dessen Enthusiasmus ansteckend wirkt. Deine Gabe liegt in der Fähigkeit, Bewegung zu erzeugen — du brichst Stagnation auf und bringst neuen Wind in festgefahrene Situationen. Du bist eine Abenteurerin des Geistes, die keine Angst vor der Flamme hat. Dein Charisma und dein Wagemut machen dich zu einer natürlichen Inspiratorin und Wegbereiterin.",
  },

  "staebe-koenigin": {
    schattenDeutung: "Die Königin der Stäbe in deinem Schatten deutet auf eine unterdrückte Leidenschaft und die Angst hin, als zu dominant, zu fordernd oder zu intensiv wahrgenommen zu werden. Vielleicht hast du gelernt, deine Strahlkraft herunterzudimmen, um andere nicht zu überfordern, oder du trägst die Wunde einer Frau, deren Feuer als bedrohlich empfunden wurde. Dein Schatten-Thema ist die Ambivalenz gegenüber deiner eigenen Macht — du willst leuchten, fürchtest aber die Konsequenzen. Die Einladung: Dein Feuer ist ein Geschenk, kein Vergehen.",
    lichtDeutung: "Die Königin der Stäbe in deinem Licht zeigt eine magnetische Persönlichkeit und eine natürliche Verbindung zwischen Leidenschaft und Weisheit. Du bist jemand, der das Feuer meisterhaft beherrscht — nicht durch Unterdrückung, sondern durch bewusstes Lenken. Deine Wärme ist einladend, dein Charisma authentisch, deine Kreativität unerschöpflich. Du inspirierst andere, indem du einfach du selbst bist. Du bist eine Königin des Feuers, die zeigt, dass Weiblichkeit und Kraft keine Gegensätze sind, sondern eine unwiderstehliche Verbindung.",
  },

  "staebe-koenig": {
    schattenDeutung: "Der König der Stäbe in deinem Schatten spricht von einem Drang zur Dominanz und der Angst, die Führung abzugeben. Vielleicht hat eine Erfahrung in dir die Überzeugung geprägt, dass nur du die richtige Vision hast und dass Delegation gleichbedeutend mit Kontrollverlust ist. Dein Schatten-König zeigt sich als Tyrann der Begeisterung — jemand, der andere mit seiner Energie überrollt statt zu inspirieren. Die Einladung: Wahre Führung entzündet das Feuer in anderen, statt sie im eigenen Feuer zu verbrennen.",
    lichtDeutung: "Der König der Stäbe in deinem Licht offenbart eine natürliche Meisterschaft über die kreative Lebenskraft und die Fähigkeit, große Visionen in die Tat umzusetzen. Du bist ein visionärer Anführer, der andere mit seinem Feuer entzündet, ohne sie zu verbrennen. Deine Gabe liegt in der Verbindung von unternehmerischem Geist und spiritueller Tiefe — du handelst aus Leidenschaft und innerem Auftrag heraus. Du bist ein König des Feuers, der zeigt, dass Macht und Integrität Hand in Hand gehen können.",
  },

  // ==========================================================================
  // KELCHE / WASSER (14 Karten)
  // ==========================================================================

  "kelche-ass": {
    schattenDeutung: "Das Ass der Kelche in deinem Schatten offenbart eine tiefe Angst davor, dein Herz wirklich zu öffnen. Vielleicht hast du so viel Schmerz erfahren, dass du glaubst, Liebe sei immer mit Verlust verbunden. Dein Schatten-Thema ist die Unfähigkeit, emotionale Geschenke anzunehmen — du sabotierst neue Anfänge der Liebe, weil du den Fall fürchtest, der auf das Hochgefühl folgen könnte. Der überflutende Kelch steht vor dir, aber du traust dich nicht zu trinken. Die Einladung: Dein Herz ist stärker, als du denkst — es kann Liebe halten.",
    lichtDeutung: "Das Ass der Kelche in deinem Licht zeigt eine tiefe emotionale Offenheit und die Fähigkeit, Liebe in ihrer reinsten Form zu empfangen und zu geben. Du trägst einen überfließenden Kelch in dir — eine Quelle der Empathie, Kreativität und emotionalen Intelligenz, die nie versiegt. Deine Gabe ist es, den ersten Schluck aus dem Kelch des neuen Anfangs zu wagen und die Süße des Lebens vollständig zu schmecken. Du bist eine Hüterin der emotionalen Wahrheit, deren offenes Herz ein heiliger Raum für andere ist.",
  },

  "kelche-zwei": {
    schattenDeutung: "Die Zwei der Kelche in deinem Schatten deutet auf eine verborgene Angst vor wahrer Intimität und Gleichwertigkeit in Beziehungen hin. Vielleicht versteckst du dich hinter einer Rolle — der Helferin, der Starken, der Unabhängigen — um echte Verletzlichkeit zu vermeiden. Dein Schatten-Thema ist die Überzeugung, dass du in einer gleichberechtigten Verbindung etwas von dir selbst verlierst, oder die Angst, dass du nicht genug bist, wenn der andere dich wirklich kennenlernt. Die Einladung: Wahre Verbindung beginnt dort, wo die Masken fallen.",
    lichtDeutung: "Die Zwei der Kelche in deinem Licht zeigt eine außergewöhnliche Fähigkeit, tiefe und gleichberechtigte Verbindungen zu schaffen. Du trägst die Gabe der emotionalen Resonanz in dir — du spürst intuitiv, was ein Gegenüber braucht, und kannst einen Raum der authentischen Begegnung halten. Deine Beziehungen sind keine Abhängigkeiten, sondern Partnerschaften der Seelen. Du bist eine Meisterin des Miteinanders, die versteht, dass wahre Verbindung entsteht, wenn zwei ganze Menschen sich begegnen, nicht zwei halbe.",
  },

  "kelche-drei": {
    schattenDeutung: "Die Drei der Kelche in deinem Schatten spricht von einer Wunde rund um Zugehörigkeit und Gemeinschaft. Vielleicht hast du dich als Kind ausgeschlossen gefühlt oder die Erfahrung gemacht, dass Freundinnen sich gegen dich wenden. Dein Schatten-Thema ist die Angst, dass Freude geteilt werden muss, um gültig zu sein, oder die Überzeugung, dass du nur dann dazugehörst, wenn du eine bestimmte Rolle spielst. Die Drei Kelche werden erhoben, aber du fragst dich heimlich, ob einer davon wirklich für dich ist.",
    lichtDeutung: "Die Drei der Kelche in deinem Licht offenbart eine natürliche Gabe für Gemeinschaft, Freundschaft und geteilte Freude. Du bist jemand, der Menschen zusammenbringt und Momente der Verbundenheit erschafft, die alle Beteiligten nähren. Deine emotionale Großzügigkeit und dein aufrichtiges Interesse an anderen machen dich zu einem Ankerpunkt in deinem sozialen Umfeld. Du verstehst, dass Freude sich multipliziert, wenn sie geteilt wird. Du bist eine Feiernde des Lebens, die zeigt, dass Gemeinschaft eine heilige Praxis ist.",
  },

  "kelche-vier": {
    schattenDeutung: "Die Vier der Kelche in deinem Schatten zeigt eine tiefe emotionale Abstumpfung und die Tendenz, die Geschenke des Lebens zu übersehen, weil du in Enttäuschung und Apathie gefangen bist. Vielleicht bist du so mit dem beschäftigt, was dir fehlt, dass du nicht siehst, was bereits da ist. Dein Schatten-Thema ist die emotionale Verschlossenheit, die sich als Anspruchsdenken tarnt — nichts scheint gut genug, weil du Angst hast, erneut verletzt zu werden. Die Einladung: Der vierte Kelch, der dir gereicht wird, enthält genau das, was deine Seele braucht.",
    lichtDeutung: "Die Vier der Kelche in deinem Licht zeigt eine kostbare Fähigkeit zur emotionalen Unterscheidung und zur bewussten Wahl. Du lässt dich nicht von jeder glitzernden Möglichkeit ablenken, sondern prüfst mit deinem Herzen, was wirklich zu dir passt. Deine innere Stille ist kein Zeichen von Desinteresse, sondern von tiefem Lauschen. Du bist jemand, der den Mut hat, 'Nein' zu sagen, um Raum für das richtige 'Ja' zu schaffen. Deine Kontemplation ist eine Superkraft in einer Welt der Überreizung.",
  },

  "kelche-fuenf": {
    schattenDeutung: "Die Fünf der Kelche in deinem Schatten spricht von einem Trauerprozess, der nie abgeschlossen wurde — einem Verlust, der wie ein stiller Strom unter der Oberfläche deines Lebens fließt. Vielleicht klebst du so sehr an dem, was du verloren hast, dass du die zwei Kelche nicht siehst, die noch aufrecht hinter dir stehen. Dein Schatten-Thema ist die Identifikation mit dem Schmerz: Du hast dich so an die Trauer gewöhnt, dass sie zu einem Teil deiner Identität geworden ist. Die Einladung: Hinter dir wartet noch Liebe — dreh dich um.",
    lichtDeutung: "Die Fünf der Kelche in deinem Licht offenbart eine tiefe emotionale Reife und die Fähigkeit, Verlust in Weisheit zu verwandeln. Du hast durch Trauer hindurchgefühlt und dadurch ein Mitgefühl entwickelt, das andere berührt und heilt. Deine Gabe liegt in der Ehrlichkeit, mit der du über Schmerz sprichst, ohne darin zu ertrinken. Du bist jemand, der andere in ihrer Trauer begleiten kann, weil du den Weg selbst gegangen bist. Dein verwandelter Schmerz ist dein größtes Werkzeug des Mitgefühls.",
  },

  "kelche-sechs": {
    schattenDeutung: "Die Sechs der Kelche in deinem Schatten deutet auf eine unbewusste Sehnsucht nach der Vergangenheit hin, die dich daran hindert, im Jetzt anzukommen. Vielleicht idealisierst du eine Kindheit, die so nie existiert hat, oder du hältst an alten Beziehungsmustern fest, weil das Vertraute sich sicherer anfühlt als das Unbekannte. Dein Schatten-Thema ist die Nostalgie als Flucht: Du schaust zurück, um dem Schmerz des Hier und Jetzt auszuweichen. Die Einladung: Die Blumen der Vergangenheit sind schön, aber dein Garten wächst im Jetzt.",
    lichtDeutung: "Die Sechs der Kelche in deinem Licht zeigt eine wunderbare Verbindung zum inneren Kind und die Fähigkeit, die Unschuld und Freude vergangener Zeiten als Kraftquelle zu nutzen. Du trägst die Gabe in dir, in jedem Moment die Magie des Anfangs wiederzufinden und die süße Einfachheit des Lebens zu schmecken. Deine emotionale Erinnerung ist ein Schatz — du bewahrst die Essenz schöner Erfahrungen und teilst sie großzügig mit anderen. Du bist eine Hüterin der Unschuld, deren Herz nie ganz erwachsen geworden ist.",
  },

  "kelche-sieben": {
    schattenDeutung: "Die Sieben der Kelche in deinem Schatten offenbart eine Tendenz zur Illusion und zum Wunschdenken, die dich daran hindert, klare Entscheidungen zu treffen. Du verlierst dich in Fantasien und Möglichkeiten, die wie Seifenblasen schillern, aber keinen Boden unter den Füßen haben. Dein Schatten-Thema ist die Angst vor der Realität — denn wenn du dich für einen Kelch entscheidest, verlierst du die sechs anderen. Die Einladung: Nicht alle Träume sind deine Träume. Lerne zu unterscheiden, welche Sehnsucht wirklich deiner Seele gehört.",
    lichtDeutung: "Die Sieben der Kelche in deinem Licht zeigt eine außergewöhnliche Vorstellungskraft und die Fähigkeit, in Möglichkeiten zu denken, die andere nicht sehen. Dein innerer Kosmos ist reich und vielfarbig — du trägst ganze Welten in dir, die darauf warten, geboren zu werden. Deine Gabe liegt in der kreativen Vision und dem Mut, das Unsichtbare sichtbar zu machen. Du bist eine Traumweberin, die versteht, dass Imagination der erste Schritt zur Manifestation ist. Dein reiches Innenleben ist keine Flucht, sondern die Quelle deiner Schöpferkraft.",
  },

  "kelche-acht": {
    schattenDeutung: "Die Acht der Kelche in deinem Schatten spricht von einer tiefen Wunde des Weglaufens — der Gewohnheit, Situationen, Menschen und Gefühle zu verlassen, bevor der Schmerz zu groß wird. Vielleicht hast du gelernt, dass Fortgehen sicherer ist als Bleiben, und suchst immer nach dem Nächsten, Besseren, statt dich dem zu stellen, was ist. Dein Schatten-Thema ist die Angst vor emotionaler Tiefe und die Verwechslung von Aufbruch mit Flucht. Die Einladung: Manchmal liegt die wahre Reise darin, zu bleiben und hinzuschauen.",
    lichtDeutung: "Die Acht der Kelche in deinem Licht offenbart den Mut, das Vertraute zu verlassen, wenn es nicht mehr deiner Wahrheit entspricht. Du trägst die seltene Fähigkeit in dir, loszulassen, was dich nicht mehr nährt, auch wenn es schmerzt. Dein Aufbruch ist kein Weglaufen, sondern ein Auf-dich-Zugehen — ein heiliger Akt der Selbstachtung. Du bist eine Pilgerin der Seele, die versteht, dass manchmal der einzige Weg zur Heilung der Weg in die Nacht hinaus ist. Dein Loslassen macht Platz für das, was wirklich zu dir gehört.",
  },

  "kelche-neun": {
    schattenDeutung: "Die Neun der Kelche in deinem Schatten deutet auf eine verborgene Sattheit und Selbstgefälligkeit hin, die dein weiteres Wachstum blockiert. Vielleicht hast du dir eine komfortable emotionale Welt aufgebaut und verwechselst Bequemlichkeit mit Erfüllung. Dein Schatten-Thema ist die Angst, dass es jenseits deiner aktuellen Zufriedenheit noch mehr gibt — und dass du dich dann bewegen müsstest. Oder du trägst den Glauben, dass du Glück nicht verdienst und wartest auf den Moment, in dem es dir wieder genommen wird.",
    lichtDeutung: "Die Neun der Kelche in deinem Licht zeigt eine tiefe emotionale Zufriedenheit und die Fähigkeit, die Fülle des Lebens wirklich zu genießen. Du trägst die seltene Weisheit in dir, dass Glück keine äußere Bedingung braucht, sondern ein innerer Zustand ist. Deine neun Kelche stehen wie ein Regenbogen hinter dir — Zeugen all der Wünsche, die du dir bereits erfüllt hast. Du bist eine Meisterin der Dankbarkeit, deren Zufriedenheit ansteckend wirkt und andere daran erinnert, dass das Gute bereits da ist.",
  },

  "kelche-zehn": {
    schattenDeutung: "Die Zehn der Kelche in deinem Schatten offenbart eine schmerzhafte Sehnsucht nach dem perfekten Familienglück, das vielleicht nie war oder nie sein wird. Vielleicht trägst du die Wunde einer zerbrochenen Familie und projizierst deine unerfüllten Bedürfnisse auf ein idealisiertes Bild von Harmonie. Dein Schatten-Thema ist die Unfähigkeit, das Unvollkommene zu akzeptieren — du jagst einem Regenbogen nach, der immer am Horizont bleibt. Die Einladung: Dein Zuhause entsteht nicht durch perfekte Umstände, sondern durch deine Fähigkeit zu lieben, was ist.",
    lichtDeutung: "Die Zehn der Kelche in deinem Licht zeigt eine tiefe Fähigkeit, emotionale Erfüllung und harmonische Verbindungen zu schaffen. Du trägst den Regenbogen in deinem Herzen — die Gabe, einen Raum der bedingungslosen Liebe zu halten, in dem alle sein dürfen, wie sie sind. Dein Zuhause ist nicht nur ein Ort, sondern ein Gefühl, das du überall hin mitnimmst. Du bist eine Weberin emotionaler Geborgenheit, die versteht, dass wahres Glück in der Verbundenheit liegt. Dein Herz ist groß genug für all die Liebe, die du verdienst.",
  },

  "kelche-bube": {
    schattenDeutung: "Der Bube der Kelche in deinem Schatten spricht von einer verdrängten emotionalen Sensibilität und der Angst, als zu weich, zu verletzlich oder zu kindlich wahrgenommen zu werden. Vielleicht hast du dein zartes Herz hinter einer coolen Fassade versteckt, weil du gelernt hast, dass Gefühle Schwäche sind. Dein Schatten-Thema ist die Entfremdung von deiner emotionalen Intelligenz — du spürst tief, erlaubst dir aber nicht, danach zu handeln. Die Einladung: Der Fisch, der aus deinem Kelch springt, ist eine Botschaft deiner Seele. Hör hin.",
    lichtDeutung: "Der Bube der Kelche in deinem Licht offenbart eine wunderbare emotionale Offenheit und die Fähigkeit, mit staunenden Augen durch die Welt zu gehen. Du empfängst emotionale und kreative Botschaften, die wie Geschenke aus einer unsichtbaren Welt zu dir kommen. Deine Sensibilität ist keine Schwäche, sondern dein feinstes Instrument — damit spürst du Stimmungen, Bedürfnisse und unausgesprochene Wahrheiten. Du bist ein Gefäß für poetische Eingebungen und kreative Inspiration. Dein offenes Herz ist ein Portal zu tieferer Wahrnehmung.",
  },

  "kelche-ritter": {
    schattenDeutung: "Der Ritter der Kelche in deinem Schatten zeigt eine Tendenz zur emotionalen Idealisierung und zum Retterkomplex. Vielleicht suchst du in anderen die Perfektion, die du in dir selbst nicht findest, oder du definierst dich über die Rolle des romantischen Helden, der andere aus ihrem Schmerz erlöst. Dein Schatten-Thema ist die Flucht in die Romantik, um der Realität auszuweichen — du lebst lieber im Film deiner Sehnsüchte als im echten Leben. Die Einladung: Die größte Romanze wartet nicht da draußen, sondern in der Begegnung mit dir selbst.",
    lichtDeutung: "Der Ritter der Kelche in deinem Licht zeigt eine tiefe romantische Seele und die Fähigkeit, die Welt mit den Augen der Liebe zu betrachten. Du trägst eine Poesie in dir, die das Gewöhnliche in etwas Magisches verwandelt. Deine emotionale Tiefe und dein Sinn für Schönheit machen dich zu einem Menschen, der andere in ihren verletzlichsten Momenten berührt. Du bist ein Ritter des Herzens, der mit Mitgefühl statt mit dem Schwert kämpft. Deine Gabe ist es, die Schönheit auch im Zerbrochenen zu sehen und darüber zu sprechen.",
  },

  "kelche-koenigin": {
    schattenDeutung: "Die Königin der Kelche in deinem Schatten deutet auf ein Übermaß an Empathie hin, das zur emotionalen Überschwemmung führt. Du nimmst die Gefühle anderer so tief in dich auf, dass du nicht mehr unterscheiden kannst, was dein Schmerz ist und was der eines anderen. Dein Schatten-Thema ist die Selbstauflösung durch Mitgefühl — du gibst so viel von deiner emotionalen Substanz, dass dein eigener Kelch leer läuft. Die Einladung: Eine leere Königin kann niemanden nähren. Fülle zuerst deinen eigenen Kelch, bevor du gießt.",
    lichtDeutung: "Die Königin der Kelche in deinem Licht offenbart eine meisterhafte emotionale Intelligenz und die Fähigkeit, einen Raum der bedingungslosen Annahme zu halten. Du bist eine intuitive Heilerin, deren Einfühlungsvermögen so tief reicht, dass du die unausgesprochenen Bedürfnisse anderer erkennst und ihnen einen Spiegel ihrer eigenen Schönheit vorhältst. Dein Kelch ist ein Ozean des Mitgefühls, aus dem andere trinken dürfen. Du bist die Mutter aller Gefühle — jemand, der alle Emotionen willkommen heißt und in Liebe verwandelt.",
  },

  "kelche-koenig": {
    schattenDeutung: "Der König der Kelche in deinem Schatten spricht von einer unterdrückten emotionalen Tiefe und der Angst, die Kontrolle über die eigenen Gefühle zu verlieren. Vielleicht hast du gelernt, dass ein wahrer König nicht weint und dass emotionale Verletzlichkeit ein Zeichen von Schwäche ist. Dein Schatten-Thema ist die Abspaltung: Du sitzt auf deinem Thron über den Wassern, aber erlaubst dir nicht, in sie einzutauchen. Die Einladung: Wahre emotionale Meisterschaft liegt nicht in der Kontrolle, sondern im bewussten Fühlen des gesamten Spektrums.",
    lichtDeutung: "Der König der Kelche in deinem Licht zeigt eine reife emotionale Weisheit und die Fähigkeit, tiefe Gefühle mit innerer Ruhe zu verbinden. Du bist ein Fels in der Brandung — jemand, der alle Wellen des Lebens reitet, ohne unterzugehen. Deine Gabe liegt in der emotionalen Führung: Du schaffst Räume, in denen andere sich sicher genug fühlen, um ihre Masken abzulegen. Du bist ein König des Mitgefühls, der zeigt, dass Stärke und Sensibilität gemeinsam den weisesten aller Herrscher erschaffen. Dein ruhiges Herz ist ein Hafen für Suchende.",
  },

  // ==========================================================================
  // SCHWERTER / LUFT (14 Karten)
  // ==========================================================================

  "schwerter-ass": {
    schattenDeutung: "Das Ass der Schwerter in deinem Schatten offenbart eine schneidende mentale Schärfe, die sich gegen dich selbst richtet. Dein innerer Kritiker führt dieses Schwert mit gnadenloser Präzision — jeder Gedanke wird zum Urteil, jede Idee zum Objekt der Zerlegung. Dein Schatten-Thema ist die Überidentifikation mit dem Verstand und die Angst, dass du nichts wert bist, wenn du nicht recht hast. Das Schwert der Klarheit wird zur Waffe der Selbstzerstörung. Die Einladung: Richte die Klinge nicht gegen dich, sondern schneide das Falsche vom Wahren.",
    lichtDeutung: "Das Ass der Schwerter in deinem Licht zeigt eine durchdringende geistige Klarheit und die Fähigkeit, zum Kern jeder Wahrheit vorzudringen. Du trägst ein Schwert der Erkenntnis in dir, das Nebel durchschneidet und Illusionen zerschlägt. Dein scharfer Verstand ist keine kalte Waffe, sondern ein Werkzeug der Befreiung — du hilfst anderen, klar zu sehen und kluge Entscheidungen zu treffen. Du bist eine Meisterin des Durchblicks, deren Worte wie frische Luft wirken. Deine intellektuelle Kraft ist ein Geschenk, das die Welt braucht.",
  },

  "schwerter-zwei": {
    schattenDeutung: "Die Zwei der Schwerter in deinem Schatten spricht von einer inneren Patt-Situation — zwei Wahrheiten, die sich scheinbar gegenseitig ausschließen, und die lähmende Weigerung, eine Entscheidung zu treffen. Vielleicht hast du gelernt, dass jede Wahl Verlust bedeutet, und sitzt deshalb mit verbundenen Augen zwischen deinen Schwertern, hoffend, dass jemand anderes für dich entscheidet. Dein Schatten-Thema ist die Angst vor der Verantwortung, die mit klarer Positionierung einhergeht. Die Einladung: Nimm die Augenbinde ab — du weißt bereits, was richtig ist.",
    lichtDeutung: "Die Zwei der Schwerter in deinem Licht zeigt eine bemerkenswerte Fähigkeit zur diplomatischen Balance und zum Abwägen verschiedener Perspektiven. Du trägst die Gabe in dir, beide Seiten einer Medaille gleichzeitig zu sehen und zwischen scheinbaren Gegensätzen eine Synthese zu finden. Deine emotionale Intelligenz und dein analytischer Verstand arbeiten in perfekter Balance zusammen. Du bist eine Vermittlerin, die Konflikte nicht durch Parteinahme löst, sondern durch ein tieferes Verständnis dessen, was alle Beteiligten wirklich brauchen.",
  },

  "schwerter-drei": {
    schattenDeutung: "Die Drei der Schwerter in deinem Schatten zeigt eine unverarbeitete Herzenswunde, die wie drei Klingen in deiner Brust steckt. Vielleicht trägst du den Schmerz eines Verrats, einer Ablehnung oder eines Herzbruchs, der nie vollständig betrauert wurde. Dein Schatten-Thema ist die Gewohnheit, den Schmerz entweder zu dramatisieren oder zu verdrängen — beides hält die Wunde offen. Du identifizierst dich so stark mit dem Schmerz, dass du Angst hast, wer du ohne ihn wärst. Die Einladung: Zieh die Schwerter heraus — ja, es blutet, aber es heilt.",
    lichtDeutung: "Die Drei der Schwerter in deinem Licht offenbart eine tiefe Fähigkeit, durch den Schmerz hindurch zur Wahrheit zu gelangen. Du hast gelernt, dass das offene Herz auch das verwundete Herz ist, und trägst diese Weisheit mit Würde. Deine Ehrlichkeit über den eigenen Schmerz gibt anderen die Erlaubnis, ebenfalls zu fühlen. Du bist eine Wahrheitssprecherin, die weiß, dass manchmal die schmerzlichste Erkenntnis auch die befreiendste ist. Dein Mut, die Wahrheit anzuschauen, auch wenn sie wehtut, ist ein kostbares Geschenk an dich und die Welt.",
  },

  "schwerter-vier": {
    schattenDeutung: "Die Vier der Schwerter in deinem Schatten deutet auf eine Flucht in die Erstarrung hin — du legst dich zur Ruhe, nicht weil du Frieden gefunden hast, sondern weil du vor dem Leben kapituliert hast. Vielleicht verwechselst du emotionale Betäubung mit innerer Stille, oder du nutzt Rückzug als Vermeidungsstrategie. Dein Schatten-Thema ist die Angst vor dem Wiederaufstehen, weil du weißt, dass das Leben dann weitergeht und neue Herausforderungen bringt. Die Einladung: Wahre Ruhe ist nicht Flucht — sie ist bewusstes Sammeln der Kräfte für den nächsten Schritt.",
    lichtDeutung: "Die Vier der Schwerter in deinem Licht zeigt eine kostbare Fähigkeit zur bewussten Regeneration und mentalen Stille. Du verstehst es, zur richtigen Zeit innezuhalten und dem Geist die Ruhe zu schenken, die er für klare Entscheidungen braucht. Deine Gabe liegt im bewussten Rückzug — du weißt, dass Pausen keine Schwäche sind, sondern die Quelle wahrer Stärke. Du bist eine Meisterin der Meditation und der inneren Einkehr, die in der Stille Antworten findet, die im Lärm des Alltags untergehen würden.",
  },

  "schwerter-fuenf": {
    schattenDeutung: "Die Fünf der Schwerter in deinem Schatten offenbart ein schmerzhaftes Muster von Sieg um jeden Preis — oder die Wunde desjenigen, der immer verliert. Vielleicht hast du gelernt, dass Konflikte nur Gewinner und Verlierer kennen, und spielst dieses Spiel bis zur Erschöpfung. Dein Schatten-Thema ist die Überzeugung, dass Nachgeben gleichbedeutend mit Versagen ist, oder die Gewohnheit, in Auseinandersetzungen unter deinem eigenen Wert zu agieren. Die Einladung: Der wichtigste Sieg ist der über dein eigenes Ego. Wahre Stärke liegt im ehrenvollen Rückzug.",
    lichtDeutung: "Die Fünf der Schwerter in deinem Licht zeigt eine scharfsinnige Fähigkeit, die Dynamiken von Macht und Konflikt zu durchschauen. Du verstehst intuitiv, wann es sich lohnt zu kämpfen und wann strategischer Rückzug die klügere Wahl ist. Deine Gabe liegt in der ehrlichen Analyse — du benennst, was andere nicht sehen wollen, und hilfst dadurch, destruktive Muster zu durchbrechen. Du bist eine Strategin des Bewusstseins, die weiß, dass der wahre Sieg darin besteht, Konflikte in Erkenntnisse zu verwandeln.",
  },

  "schwerter-sechs": {
    schattenDeutung: "Die Sechs der Schwerter in deinem Schatten spricht von einem Übergang, den du verzögerst — du weißt, dass du weiterziehen musst, aber ein Teil von dir klammert sich ans Ufer des Bekannten. Vielleicht trägst du die Angst, dass auf der anderen Seite des Wassers nicht Frieden wartet, sondern nur neuer Schmerz. Dein Schatten-Thema ist die Unfähigkeit, Abschied zu nehmen, oder die Gewohnheit, Probleme mitzunehmen statt sie am Ufer zurückzulassen. Die Einladung: Das Boot fährt — mit oder ohne dich. Steig ein und lass die Schwerter stehen.",
    lichtDeutung: "Die Sechs der Schwerter in deinem Licht zeigt eine weise Fähigkeit, schwierige Übergänge bewusst und sanft zu gestalten. Du trägst die Gabe in dir, dich und andere sicher durch stürmische Gewässer zu navigieren, ohne dabei den Kompass zu verlieren. Dein ruhiger Verstand und dein klares Denken helfen dir, auch in emotionalen Turbulenzen den Kurs zu halten. Du bist eine Lotsin der Seele, die versteht, dass Heilung manchmal bedeutet, das Vertraute hinter sich zu lassen und dem ruhigeren Wasser entgegenzufahren.",
  },

  "schwerter-sieben": {
    schattenDeutung: "Die Sieben der Schwerter in deinem Schatten offenbart ein Muster der Heimlichkeit und Selbsttäuschung. Vielleicht hast du gelernt, dass Offenheit bestraft wird, und trägst seitdem Masken, von denen du manche selbst vergessen hast. Dein Schatten-Thema ist die Angst, entdeckt zu werden — nicht als Betrügerin, sondern als Mensch mit Fehlern und Schwächen. Du schleichst auf Zehenspitzen durch dein eigenes Leben und nimmst dir weniger, als dir zusteht. Die Einladung: Leg die gestohlenen Schwerter ab und nimm das, was dir wirklich gehört — offen und aufrecht.",
    lichtDeutung: "Die Sieben der Schwerter in deinem Licht zeigt eine außergewöhnliche Klugheit und die Fähigkeit, strategisch und unkonventionell zu denken. Du durchschaust Situationen schnell und findest kreative Lösungen, wo andere nur Regeln sehen. Deine Gabe liegt in der geistigen Beweglichkeit — du denkst um die Ecke und entdeckst Wege, die andere übersehen. Du bist keine Regelverbrecherin, sondern eine Regelneuerfinderin, die versteht, dass manchmal der unorthodoxe Weg der einzige ist, der zum Ziel führt.",
  },

  "schwerter-acht": {
    schattenDeutung: "Die Acht der Schwerter in deinem Schatten zeigt ein Gefängnis, das du dir selbst gebaut hast — aus Ängsten, Überzeugungen und Denkmustern, die dich fesseln, obwohl die Tür offen steht. Vielleicht glaubst du, dass du keine andere Wahl hast, oder dass Freiheit für andere reserviert ist, nicht für dich. Dein Schatten-Thema ist die erlernte Hilflosigkeit und die Überzeugung, dass Veränderung unmöglich ist. Die Einladung: Die Schwerter, die dich umgeben, sind nicht in den Boden gerammt — sie sind nur hingestellt. Du kannst jederzeit zwischen ihnen hindurchgehen.",
    lichtDeutung: "Die Acht der Schwerter in deinem Licht offenbart eine tiefe Fähigkeit, mentale Grenzen zu erkennen und zu überwinden. Du hast die seltene Weisheit, zu verstehen, dass die meisten Gefängnisse im Kopf existieren — und dass der Schlüssel zur Befreiung im Bewusstsein liegt. Deine Gabe ist es, anderen die Augenbinde abzunehmen und ihnen zu zeigen, dass sie freier sind, als sie denken. Du bist eine Befreierin des Geistes, deren Klarheit die Mauern der Illusion zum Einsturz bringt. Dein Durchblick ist Medizin für die Ängstlichen.",
  },

  "schwerter-neun": {
    schattenDeutung: "Die Neun der Schwerter in deinem Schatten spricht von nächtlichen Ängsten und dem inneren Dialog, der dich nicht schlafen lässt. Deine Sorgen sind wie neun Schwerter an der Wand — sie hängen über dir und werfen Schatten, die größer sind als die reale Bedrohung. Dein Schatten-Thema ist die Katastrophisierung: Dein Geist malt die schlimmsten Szenarien aus und hält sie für Prophezeiungen statt für Fantasien. Die Einladung: Die meisten Schwerter, die du fürchtest, werden nie fallen. Dein Geist ist kein Prophet — er ist ein besorgter Geschichtenerzähler.",
    lichtDeutung: "Die Neun der Schwerter in deinem Licht zeigt eine außergewöhnliche psychologische Tiefe und die Fähigkeit, auch die dunkelsten Gedanken zu erforschen, ohne darin zu ertrinken. Du hast den Mut, dich deinen Ängsten zu stellen und sie als das zu erkennen, was sie sind: Geschichten deines Geistes, nicht die Wahrheit. Deine Gabe liegt in der Schattenarbeit — du tauchst in die Tiefen des Unbewussten und bringst Schätze an die Oberfläche. Du bist eine Nachtarbeiterin der Psyche, deren Ehrlichkeit über die eigenen Abgründe anderen Mut macht.",
  },

  "schwerter-zehn": {
    schattenDeutung: "Die Zehn der Schwerter in deinem Schatten offenbart eine tiefe Erfahrung des Zusammenbruchs und die Tendenz, dich als Opfer zu definieren. Vielleicht hast du einen Moment erlebt, in dem alles zerbrochen ist, und trägst seitdem die Überzeugung, dass das Schlimmste immer wieder passieren wird. Dein Schatten-Thema ist die Dramatisierung des Schmerzes — zehn Schwerter im Rücken sind neun zu viel, aber ein Teil von dir braucht die Intensität des Leids, um sich lebendig zu fühlen. Die Einladung: Der Sonnenaufgang im Hintergrund zeigt dir — nach dem absoluten Tiefpunkt kommt das Licht.",
    lichtDeutung: "Die Zehn der Schwerter in deinem Licht zeigt eine bemerkenswerte Fähigkeit, absolute Tiefpunkte als Wendepunkte zu erkennen und zu nutzen. Du weißt aus eigener Erfahrung, dass es nach dem Zusammenbruch nur noch aufwärts geht. Deine Gabe liegt in der Resilienz und in dem unerschütterlichen Wissen, dass kein Schmerz für immer dauert. Du bist eine Phönix-Natur, die aus der totalen Zerstörung die größte Transformation gebiert. Deine Fähigkeit, nach dem Fall aufzustehen, gibt anderen die Hoffnung, die sie brauchen.",
  },

  "schwerter-bube": {
    schattenDeutung: "Der Bube der Schwerter in deinem Schatten zeigt eine nervöse intellektuelle Energie und die Tendenz, den Verstand als Waffe gegen dich selbst und andere einzusetzen. Vielleicht bist du neugierig bis zur Grenze der Taktlosigkeit, oder dein scharfer Verstand wirkt verletzend, weil du nicht gelernt hast, deine Worte mit Mitgefühl zu polstern. Dein Schatten-Thema ist die Unreife im Umgang mit der eigenen Intelligenz — du weißt viel, aber die Weisheit, dieses Wissen liebevoll einzusetzen, entwickelt sich noch. Die Einladung: Schärfe und Sanftheit schließen sich nicht aus.",
    lichtDeutung: "Der Bube der Schwerter in deinem Licht offenbart einen brillanten, wachen Geist und eine unersättliche Neugier, die die Welt mit frischen Augen betrachtet. Du stellst die Fragen, die andere nicht wagen, und dein Mut zur intellektuellen Ehrlichkeit ist erfrischend. Deine Gabe liegt in der Fähigkeit, alte Denkmuster aufzubrechen und neue Perspektiven zu eröffnen. Du bist eine Botin der geistigen Erneuerung, die mit der Schärfe einer jungen Klinge das Überflüssige vom Wesentlichen trennt. Dein wacher Geist ist ein Geschenk für jeden Raum.",
  },

  "schwerter-ritter": {
    schattenDeutung: "Der Ritter der Schwerter in deinem Schatten zeigt eine rücksichtslose mentale Aggression und die Tendenz, mit Worten zu verletzen, bevor du denkst. Du stürmst in intellektuelle Schlachten, ohne die Konsequenzen zu bedenken, und hinterlässt eine Spur verletzter Seelen. Dein Schatten-Thema ist die Verwechslung von Recht haben mit richtig handeln — du gewinnst Argumente, aber verlierst Beziehungen. Dein scharfer Geist wird zum Schwert, das wahllos zuschlägt. Die Einladung: Wahre intellektuelle Stärke zeigt sich in der Fähigkeit, das Schwert auch einmal in der Scheide zu lassen.",
    lichtDeutung: "Der Ritter der Schwerter in deinem Licht zeigt eine beeindruckende geistige Schnelligkeit und den Mut, für die Wahrheit einzustehen. Du bist jemand, der nicht zögert, wenn es darum geht, das Richtige zu tun, und dessen Entschlossenheit Berge versetzen kann. Deine Gabe liegt in der Fähigkeit, schnell zu analysieren und entschlossen zu handeln. Du bist ein Ritter der Klarheit, der den Wind der Veränderung nicht fürchtet, sondern ihn als Antrieb nutzt. Dein scharfer Verstand, gepaart mit deinem Mut, macht dich zu einer unvergesslichen Stimme der Wahrheit.",
  },

  "schwerter-koenigin": {
    schattenDeutung: "Die Königin der Schwerter in deinem Schatten deutet auf eine emotionale Verhärtung hin, die sich hinter intellektueller Souveränität verbirgt. Vielleicht hast du nach einer schmerzhaften Erfahrung gelernt, dein Herz hinter einer Mauer aus Verstand und Unnahbarkeit zu verstecken. Dein Schatten-Thema ist die Verwechslung von Kälte mit Stärke — du schneidest emotionale Verbindungen ab, bevor sie dich verletzen können, und verlierst dabei die Wärme, die dein Leben nähren könnte. Die Einladung: Dein Schwert kann schützen, ohne zu isolieren.",
    lichtDeutung: "Die Königin der Schwerter in deinem Licht zeigt eine meisterhafte Verbindung von Intellekt und Empathie. Du trägst ein Schwert der Wahrheit, das präzise schneidet, aber nie unnötig verletzt. Deine Gabe liegt in der klaren Kommunikation und der Fähigkeit, auch schmerzhafte Wahrheiten mit Würde auszusprechen. Du bist eine Königin der Klarheit, die Grenzen setzen kann, ohne Brücken zu verbrennen. Deine geistige Unabhängigkeit und dein feiner Verstand machen dich zu einer Ratgeberin, deren Worte wie geschliffene Diamanten wirken — klar, kostbar und unvergesslich.",
  },

  "schwerter-koenig": {
    schattenDeutung: "Der König der Schwerter in deinem Schatten spricht von einem übermächtigen inneren Richter, der mit kalter Logik über alles und jeden urteilt — auch über dich selbst. Vielleicht hast du gelernt, dass Objektivität wichtiger ist als Mitgefühl, und bist zum Gefangenen deines eigenen Intellekts geworden. Dein Schatten-Thema ist die Tyrannei der Rationalität: Du zerschneidest jedes Gefühl mit dem Schwert des Verstandes, bis nichts mehr übrig bleibt als kalte Analyse. Die Einladung: Ein König ohne Herz regiert ein leeres Königreich. Verbinde Verstand und Seele.",
    lichtDeutung: "Der König der Schwerter in deinem Licht offenbart eine souveräne geistige Autorität und die Fähigkeit, komplexe Wahrheiten mit Klarheit und Integrität auszusprechen. Du bist ein Meister der fairen Urteilskraft — dein Verstand arbeitet wie ein geschliffenes Schwert, das das Wesentliche vom Unwesentlichen trennt. Deine Gabe liegt in der intellektuellen Führung, die andere nicht einschüchtert, sondern erhebt. Du bist ein König der Wahrheit, dessen Worte Gewicht haben, weil sie von Erfahrung, Weisheit und tiefer Integrität getragen werden.",
  },

  // ==========================================================================
  // MÜNZEN / ERDE (14 Karten)
  // ==========================================================================

  "muenzen-ass": {
    schattenDeutung: "Das Ass der Münzen in deinem Schatten offenbart eine tiefe Wunde rund um Selbstwert und materielle Sicherheit. Vielleicht glaubst du, dass du Fülle nicht verdienst, oder du klammerst dich so sehr an materielle Sicherheit, dass du das Wunder des Augenblicks verpasst. Dein Schatten-Thema ist die Angst vor Mangel — die Überzeugung, dass nie genug da sein wird, egal wie viel du hast. Die goldene Münze wird dir gereicht, aber deine Hand zittert. Die Einladung: Das Universum bietet dir die Saat der Fülle an — nimm sie an und pflanze sie mit Vertrauen.",
    lichtDeutung: "Das Ass der Münzen in deinem Licht zeigt eine natürliche Verbindung zur materiellen Welt und die Fähigkeit, Ideen in greifbare Realität zu verwandeln. Du trägst den goldenen Samen der Manifestation in dir — alles, was du mit Liebe und Absicht in die Erde pflanzt, wächst und gedeiht. Deine Gabe ist die Fähigkeit, Chancen zu erkennen und sie mit geduldiger Arbeit in Wohlstand zu verwandeln. Du bist eine Erdenhüterin, die versteht, dass wahre Fülle dort beginnt, wo Dankbarkeit und Handeln sich begegnen.",
  },

  "muenzen-zwei": {
    schattenDeutung: "Die Zwei der Münzen in deinem Schatten spricht von einem erschöpfenden Jonglierakt, der nie zur Ruhe kommt. Du versuchst, alle Bälle in der Luft zu halten, und lebst in der ständigen Angst, dass einer fällt. Dein Schatten-Thema ist die Unfähigkeit, Prioritäten zu setzen und die Illusion, dass Multitasking ein Zeichen von Kompetenz ist. In Wahrheit weicht dein ständiges Ausbalancieren der Frage aus: Was ist mir wirklich wichtig? Die Einladung: Du musst nicht alles gleichzeitig halten. Leg einen Ball ab und spüre die Erleichterung.",
    lichtDeutung: "Die Zwei der Münzen in deinem Licht zeigt eine bemerkenswerte Anpassungsfähigkeit und die Fähigkeit, in sich ständig verändernden Umständen Balance zu finden. Du tanzt mit dem Leben statt gegen es zu kämpfen, und deine Flexibilität ist eine wahre Stärke. Deine Gabe liegt im spielerischen Umgang mit Herausforderungen — du findest Rhythmus, wo andere nur Chaos sehen. Du bist eine Tänzerin des Lebens, die versteht, dass Balance kein statischer Zustand ist, sondern eine fortlaufende, anmutige Bewegung.",
  },

  "muenzen-drei": {
    schattenDeutung: "Die Drei der Münzen in deinem Schatten deutet auf eine Wunde rund um Anerkennung und die Angst, nicht gut genug zu sein. Vielleicht arbeitest du bis zur Erschöpfung, um zu beweisen, dass du dazugehörst, oder du verbirgst deine Fähigkeiten aus Angst vor Bewertung. Dein Schatten-Thema ist die Abhängigkeit von externer Bestätigung für deine handwerkliche Meisterschaft — du brauchst den Applaus der Meister, um deinem eigenen Können zu vertrauen. Die Einladung: Deine Arbeit spricht für sich. Du musst niemandem mehr beweisen, dass du gut genug bist.",
    lichtDeutung: "Die Drei der Münzen in deinem Licht offenbart eine natürliche Meisterschaft und die Fähigkeit, in Zusammenarbeit mit anderen Großes zu erschaffen. Du verstehst es, dein Handwerk mit Hingabe und Liebe zum Detail auszuüben und dabei andere in ihren Stärken einzubinden. Deine Gabe liegt in der kollaborativen Exzellenz — du bringst das Beste in einem Team hervor und schaffst Werke, die allein nicht möglich wären. Du bist eine Meisterin der praktischen Weisheit, deren Kompetenz und Demut andere inspirieren.",
  },

  "muenzen-vier": {
    schattenDeutung: "Die Vier der Münzen in deinem Schatten zeigt ein Muster des Festhaltens und der Knappheitsmentalität. Du klammerst dich an das, was du hast — Geld, Besitz, Kontrolle, Sicherheit — aus der tiefen Angst, dass alles verloren gehen könnte. Dein Schatten-Thema ist der innere Geizhals, der nicht nur materielle Ressourcen, sondern auch Liebe, Zeit und Energie zurückhält. Vielleicht hast du Entbehrung erlebt und trägst seitdem die Überzeugung, dass man sich nur auf sich selbst verlassen kann. Die Einladung: Festhalten erzeugt das, was du fürchtest. Fließen lassen erzeugt Fülle.",
    lichtDeutung: "Die Vier der Münzen in deinem Licht zeigt eine gesunde Fähigkeit, Grenzen zu setzen und deine Ressourcen weise zu verwalten. Du trägst die Weisheit der Sparsamkeit und des Maßhaltens in dir — nicht aus Geiz, sondern aus einem tiefen Verständnis dafür, was wirklich wertvoll ist. Deine Gabe liegt in der finanziellen und emotionalen Selbstfürsorge: Du weißt, was du brauchst, und sorgst gut für dich. Du bist eine Hüterin der Ressourcen, die versteht, dass kluge Vorsorge der Grundstein für großzügiges Geben ist.",
  },

  "muenzen-fuenf": {
    schattenDeutung: "Die Fünf der Münzen in deinem Schatten spricht von einer tiefen Erfahrung der Ausgrenzung und dem Glauben, dass du vom Reichtum des Lebens ausgeschlossen bist. Vielleicht stehst du im Schneesturm vor der erleuchteten Kirche und traust dich nicht hineinzugehen, weil du glaubst, nicht willkommen zu sein. Dein Schatten-Thema ist die Identifikation mit dem Mangel — du definierst dich über das, was dir fehlt, statt über das, was du hast. Die Einladung: Die Tür steht offen, die Wärme wartet. Du musst nur den Mut haben, sie aufzustoßen.",
    lichtDeutung: "Die Fünf der Münzen in deinem Licht offenbart eine tiefe Empathie für alle, die am Rand stehen, und die Fähigkeit, in der Dunkelheit Hoffnung zu finden. Du hast Mangel erlebt und dadurch ein Mitgefühl entwickelt, das echt und tief ist. Deine Gabe liegt darin, anderen in schweren Zeiten beizustehen, weil du den Weg selbst gegangen bist. Du bist eine Helferin der Vergessenen, die versteht, dass wahre Stärke oft in der Verwundbarkeit liegt. Dein Wissen um die Kälte macht dich zur besten Hüterin der Wärme.",
  },

  "muenzen-sechs": {
    schattenDeutung: "Die Sechs der Münzen in deinem Schatten deutet auf ein ungesundes Machtgefälle in deinen Beziehungen zum Geben und Nehmen hin. Vielleicht gibst du übermäßig, um Kontrolle oder Zuneigung zu gewinnen, oder du schämst dich, empfangen zu müssen. Dein Schatten-Thema ist die Instrumentalisierung von Großzügigkeit — du gibst, um geliebt zu werden, und nimmst, weil du keine andere Wahl siehst. Wahre Großzügigkeit hat keine Hintergedanken. Die Einladung: Prüfe ehrlich, ob dein Geben frei ist oder ob unsichtbare Fäden daran hängen.",
    lichtDeutung: "Die Sechs der Münzen in deinem Licht zeigt eine natürliche Großzügigkeit und ein feines Gespür für die Balance zwischen Geben und Empfangen. Du trägst die Weisheit in dir, dass Wohlstand zum Fließen bestimmt ist — nicht zum Horten. Deine Gabe liegt in der mühelosen Großzügigkeit, die von Herzen kommt und keine Gegenleistung erwartet. Du bist eine Meisterin des gerechten Austauschs, die versteht, dass jeder Akt des aufrichtigen Gebens auch ein Akt des Empfangens ist. Dein offenes Herz erschafft einen Kreislauf der Fülle.",
  },

  "muenzen-sieben": {
    schattenDeutung: "Die Sieben der Münzen in deinem Schatten offenbart eine quälende Ungeduld und den Zweifel, ob sich die ganze Mühe überhaupt lohnt. Du stehst vor dem Strauch, den du so sorgsam gepflegt hast, und fragst dich, ob die Früchte jemals reif werden. Dein Schatten-Thema ist die Unfähigkeit, den langsamen Rhythmus des Wachstums zu akzeptieren — du willst ernten, bevor die Saat aufgegangen ist. Oder du hast die Geduld verloren und denkst daran, den Garten aufzugeben. Die Einladung: Die Früchte reifen — aber sie reifen in ihrer Zeit, nicht in deiner.",
    lichtDeutung: "Die Sieben der Münzen in deinem Licht zeigt eine tiefe Fähigkeit zur Geduld und zum Vertrauen in organische Wachstumsprozesse. Du verstehst, dass wahre Ernte Zeit braucht und dass die besten Früchte an dem Baum reifen, den niemand zu früh geschüttelt hat. Deine Gabe liegt in der Weisheit der Gärtnerin — du weißt, wann du säen, pflegen und warten musst. Du bist eine Meisterin der langfristigen Vision, die versteht, dass nachhaltige Ergebnisse Geduld, Vertrauen und stetige Hingabe erfordern.",
  },

  "muenzen-acht": {
    schattenDeutung: "Die Acht der Münzen in deinem Schatten deutet auf ein Muster der Perfektion und des Workaholic-Syndroms hin, das dich daran hindert, das Leben jenseits der Arbeit zu genießen. Vielleicht definierst du deinen Wert ausschließlich über Leistung und hast vergessen, dass du auch ohne Produktivität wertvoll bist. Dein Schatten-Thema ist die Besessenheit mit dem Detail, die das Ganze aus dem Blick verliert — du verfeinerst endlos, statt zu vollenden. Die Einladung: Dein Wert ist nicht gleich deiner Leistung. Du darfst auch einfach sein, ohne etwas zu schaffen.",
    lichtDeutung: "Die Acht der Münzen in deinem Licht offenbart eine tiefe Hingabe ans Handwerk und die Fähigkeit, in der fokussierten Arbeit Meditation und Erfüllung zu finden. Du trägst die Gabe der Meisterschaft in dir — wenn du dich einer Sache widmest, wirst du zur Virtuosin. Deine Liebe zum Detail und dein Streben nach Exzellenz sind keine Bürde, sondern der Weg zu deiner höchsten Entfaltung. Du bist eine Handwerkerin der Seele, die versteht, dass wahre Meisterschaft nicht im Ergebnis liegt, sondern im liebevollen Prozess des Übens.",
  },

  "muenzen-neun": {
    schattenDeutung: "Die Neun der Münzen in deinem Schatten spricht von einer Angst vor wahrer Unabhängigkeit und der versteckten Überzeugung, dass du Wohlstand und Freiheit nicht allein verdienst. Vielleicht sabotierst du deinen eigenen Erfolg oder fühlst dich schuldig für das Gute in deinem Leben. Dein Schatten-Thema ist die Verwechslung von Einsamkeit mit Unabhängigkeit — du hast dir einen schönen Garten geschaffen, aber niemanden, mit dem du ihn teilst. Die Einladung: Dein Reichtum wird nicht weniger, wenn du ihn genießt. Feiere, was du erschaffen hast.",
    lichtDeutung: "Die Neun der Münzen in deinem Licht zeigt eine strahlende Selbstgenügsamkeit und die Fähigkeit, Fülle aus eigener Kraft zu erschaffen. Du stehst in deinem Garten und erntest die Früchte deiner eigenen Arbeit — unabhängig, elegant, in deiner Macht. Deine Gabe liegt in der Fähigkeit, dir selbst ein reiches und schönes Leben zu gestalten, das von innerer und äußerer Fülle zeugt. Du bist eine Königin der Selbstversorgung, die zeigt, dass Unabhängigkeit und Weiblichkeit sich wunderbar ergänzen.",
  },

  "muenzen-zehn": {
    schattenDeutung: "Die Zehn der Münzen in deinem Schatten offenbart eine belastende Verstrickung in Familienthemen und generationsübergreifende Muster. Vielleicht trägst du die Last ungelöster Konflikte deiner Vorfahren oder definierst dich über den Status deiner Familie statt über dein eigenes Sein. Dein Schatten-Thema ist die Angst vor dem Zerfall des Familiensystems, die dich daran hindert, deinen eigenen Weg zu gehen, oder die Kehrseite: die schmerzliche Sehnsucht nach der Familie, die du nie hattest. Die Einladung: Du bist mehr als dein Stammbaum. Dein wahres Erbe ist deine Seele.",
    lichtDeutung: "Die Zehn der Münzen in deinem Licht zeigt eine tiefe Verbindung zu deinen Wurzeln und die Fähigkeit, ein bleibendes Vermächtnis zu schaffen, das über dein eigenes Leben hinausreicht. Du verstehst, dass wahre Fülle nicht in Bankkonten liegt, sondern in den Werten, Traditionen und der Liebe, die du an die nächste Generation weitergibst. Deine Gabe ist es, ein Fundament zu bauen, auf dem andere wachsen können. Du bist eine Hüterin des generationsübergreifenden Wohlstands — materiell, emotional und spirituell.",
  },

  "muenzen-bube": {
    schattenDeutung: "Der Bube der Münzen in deinem Schatten spricht von einer Angst vor dem Anfang und der Überzeugung, dass du noch nicht bereit bist. Du studierst endlos, bereitest dich vor und wartest auf den perfekten Moment, der nie kommt. Dein Schatten-Thema ist die Prokrastination, die sich als Sorgfalt tarnt — du willst alles perfekt machen, bevor du startest, und verpasst dabei den natürlichen Moment des Beginns. Vielleicht hast du Angst vor dem Scheitern oder vor dem Erwachsenwerden. Die Einladung: Die Münze liegt in deiner Hand. Du musst sie nicht erst verdienen — du musst sie nur einpflanzen.",
    lichtDeutung: "Der Bube der Münzen in deinem Licht offenbart eine wunderbare Lernbereitschaft und die Fähigkeit, die Magie im Alltäglichen zu entdecken. Du trägst die Energie des ewigen Schülers in dir — demütig, neugierig, bereit, von Grund auf zu lernen. Deine Gabe liegt in der Fähigkeit, abstrakte Ideen in praktische Schritte zu übersetzen und mit Staunen und Hingabe die ersten Samen zu pflanzen. Du bist eine Entdeckerin der materiellen Welt, die versteht, dass jede Meisterreise mit einem einzigen, bewussten Schritt beginnt.",
  },

  "muenzen-ritter": {
    schattenDeutung: "Der Ritter der Münzen in deinem Schatten zeigt ein Muster der Sturheit und Stagnation, das sich als Beständigkeit tarnt. Du hältst an Wegen fest, die nicht mehr funktionieren, weil Veränderung sich wie Verrat an deinen bisherigen Bemühungen anfühlt. Dein Schatten-Thema ist die Verwechslung von Ausdauer mit Starrheit — du pflügst weiter, auch wenn der Boden längst unfruchtbar ist. Vielleicht hast du Angst, dass Richtungswechsel Schwäche bedeuten. Die Einladung: Wahre Beständigkeit liegt nicht im blinden Weitermachen, sondern im flexiblen Dienen deiner tiefsten Wahrheit.",
    lichtDeutung: "Der Ritter der Münzen in deinem Licht zeigt eine bewundernswerte Zuverlässigkeit und die Fähigkeit, Projekte mit unerschütterlicher Geduld und Beständigkeit zum Abschluss zu bringen. Du bist jemand, auf den man sich verlassen kann — dein Wort ist so fest wie der Boden unter deinen Füßen. Deine Gabe liegt in der methodischen Stärke: Du setzt einen Fuß vor den anderen, auch wenn der Weg lang ist, und erreichst so Ziele, die andere längst aufgegeben hätten. Du bist ein Ritter der Erde, dessen stille Ausdauer Berge versetzt.",
  },

  "muenzen-koenigin": {
    schattenDeutung: "Die Königin der Münzen in deinem Schatten deutet auf eine übermäßige Identifikation mit der Rolle der Versorgerin hin, die dich von deinen eigenen Bedürfnissen entfremdet. Vielleicht nährst du alle anderen und vergisst dabei, dich selbst zu nähren, oder du misst deinen Wert an deiner Fähigkeit, materielle Sicherheit zu bieten. Dein Schatten-Thema ist die Aufopferung im Namen der Fürsorge und die Unfähigkeit, Hilfe anzunehmen. Die Einladung: Eine Königin, die ihren eigenen Garten nicht gießt, verdorrt — und mit ihr verdorrt das Königreich.",
    lichtDeutung: "Die Königin der Münzen in deinem Licht offenbart eine tiefe Verbundenheit mit der Erde und die Fähigkeit, Räume der Geborgenheit und des Wohlstands zu schaffen. Du bist eine natürliche Nährerin, die alles zum Blühen bringt — Gärten, Kinder, Projekte, Gemeinschaften. Deine Gabe liegt in der praktischen Weisheit und dem feinen Gespür dafür, was ein Mensch, ein Raum oder eine Situation braucht, um zu gedeihen. Du bist eine Erdmutter im besten Sinne — jemand, in dessen Nähe die Welt sich sicher und genährt anfühlt.",
  },

  "muenzen-koenig": {
    schattenDeutung: "Der König der Münzen in deinem Schatten spricht von einer übermäßigen Fixierung auf materielle Kontrolle und den Glauben, dass dein Wert durch deinen Besitz definiert wird. Vielleicht hast du eine solide Festung des Wohlstands erbaut, aber die Mauern sind so hoch, dass kein Licht mehr hindurchdringt. Dein Schatten-Thema ist die Verwechslung von Haben mit Sein — du besitzt, aber fühlst dich innerlich leer, oder du fürchtest den Verlust so sehr, dass du die Freude am Gewonnenen nicht empfinden kannst. Die Einladung: Wahre Fülle liegt jenseits der Materie. Dein Herz ist dein größter Reichtum.",
    lichtDeutung: "Der König der Münzen in deinem Licht zeigt eine meisterhafte Fähigkeit, nachhaltigen Wohlstand zu erschaffen und gleichzeitig in Verbindung mit den wahren Werten des Lebens zu bleiben. Du bist ein weiser Verwalter der Ressourcen — jemand, der versteht, dass Reichtum zum Fließen bestimmt ist und dass wahre Sicherheit auf innerem Frieden gründet. Deine Gabe liegt in der Verbindung von geschäftlichem Scharfsinn und spiritueller Tiefe. Du bist ein König der Erde, dessen Thron auf Integrität, Großzügigkeit und der tiefen Gewissheit steht, dass Fülle für alle reicht.",
  },
};

/**
 * Gibt die Schatten- und Licht-Deutung für eine bestimmte Karte zurück.
 * Fällt auf eine generische Deutung zurück, wenn die Karte nicht gefunden wird.
 */
export function getSchattenLichtDeutung(karteId: string): SchattenLichtDeutung {
  return schattenLichtDeutungen[karteId] || {
    schattenDeutung: "Diese Karte spiegelt verborgene Themen in deiner Seele wider, die darauf warten, liebevoll angeschaut und integriert zu werden.",
    lichtDeutung: "Diese Karte zeigt dir dein strahlendes Potenzial und die Gaben, die du in die Welt tragen darfst.",
  };
}
